In [8]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import nest_asyncio
nest_asyncio.apply()

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "vscode"            

import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.dates as mdates
plt.style.use('seaborn-v0_8-dark')
params = {'legend.fontsize': 'x-large',
        'figure.figsize': (16, 9),
        'axes.labelsize': 'x-large',
        'axes.titlesize':'x-large',
        'xtick.labelsize':'x-large',
        'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)

import pandas as pd
import numpy as np
import QuantLib as ql
import rateslib as rl

import datetime
import pytz
NY_tz = pytz.timezone("America/New_York") 
CHI_tz = pytz.timezone("America/Chicago") 
UTC_tz = pytz.timezone("UTC")

import warnings
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
cache_path = r"C:\Users\chris\clee\project-oasis\private\sdranalytics\.cache"
start = NY_tz.localize(datetime.datetime(2025, 12, 29, 7, 0))
end = NY_tz.localize(datetime.datetime(2025, 12, 29, 17, 30))

In [10]:
# from MDP.FixedRateBonds.FixedRateBondsMDP import FixedRateBondsMDP

# usts_mdp = FixedRateBondsMDP(source="USTS_WEBULL_WSJ_LIVE-RL")
# usts_mdp.

from MDP.FixedRateBonds.TRADINGVIEW.TradingViewFetcher import fetch_cusip_eod_timeseries_parallel 

fetch_cusip_eod_timeseries_parallel(cusips=["912810UA4", "912810UC0"], start=datetime.date(2025, 12, 1), end=datetime.date(2025, 12, 31))

                     912810UA4  912810UC0
datetime
2025-12-01 16:55:00    98.1406    92.2305
2025-12-02 16:55:00    97.8125    91.8828
2025-12-03 16:55:00    97.1953    91.3281
2025-12-07 16:55:00    97.0820    91.2031
2025-12-08 16:55:00    96.9258    91.0742
2025-12-09 16:55:00    97.2383    91.3633
2025-12-10 16:55:00    97.0664    91.2070
2025-12-11 16:55:00    96.4375    90.5781
2025-12-14 16:55:00    96.3906    90.5156
2025-12-15 16:55:00    96.9219    91.0430
2025-12-16 16:55:00    96.7031    90.8086
2025-12-17 16:55:00    97.0703    91.1836
2025-12-18 16:55:00    96.8047    90.9141
2025-12-21 16:55:00    96.5703    90.7031
2025-12-22 16:55:00    96.7461    90.8711
2025-12-23 16:55:00    97.2344    91.2852
2025-12-24 16:55:00    97.2578    91.2891
2025-12-25 16:55:00    96.8828    90.9375
2025-12-28 16:55:00    97.1016    91.2266
2025-12-29 16:55:00    97.0391    91.1250
2025-12-30 16:55:00    96.7578    90.8438
2025-12-31 16:55:00    96.3086    90.4141

In [6]:
from SDRUtils.products import USD_SOFR_SwapProduct

product = USD_SOFR_SwapProduct()
df = product.build_classification_dataframe(start=start, end=end, cache_path=cache_path)

df

CACHE HIT...: 100%|██████████| 1/1 [00:00<00:00, 53.81it/s]
Classifying Trades: 100%|██████████| 1871/1871 [00:10<00:00, 176.21it/s]
FETCHING DELIVERY BASKETS...:   0%|          | 0/6 [00:00<?, ?it/s]

KeyError: 'FedInvest snapshot missing CUSIP 91282CPR6 for 2025-12-29 14:00:00-06:00'

In [194]:
df["invoice_swap_ticker"].value_counts()

KeyError: 'invoice_swap_ticker'

In [184]:
# df.tail(1).to_dict(orient="records")
df[(df["effective_date"].dt.date == datetime.date(2026, 3, 31))]

,trade_id,execution_timestamp,effective_date,expiration_date,product_type,tenor_years,tenor_label,is_forward,forward_start_years,forward_label,...,Cleared,package_legs,matched_ust_maturity,ust_cusip,ust_oi,ust_issue_date,swap_maturity_date,matched_ust_maturity_trade_confidence,invoice_swap_ticker,risk
974,1570380985000000401,2025-12-29 12:38:22+00:00,2026-03-31,2026-12-31 00:00:00,OIS_SWAP,0.763889,9M,True,0.255556,3M,...,I,[1570380985000000401],True,91282CME8,2-Year,2024-12-31,2026-12-31,high,NaN,5533.409236
978,1570476216000000301,2025-12-29 12:43:06+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570476216000000301],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,25221.346128
982,1570527359000000301,2025-12-29 12:45:25+00:00,2026-03-31,2032-11-30 00:00:00,OIS_SWAP,6.766667,7Y,True,0.255556,3M,...,I,[1570527359000000301],True,91282CPM7,7-Year,2025-12-01,2032-11-30,high,TYB,100245.298930
984,1570638065000001001,2025-12-29 12:54:12+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570638065000001001],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,99712.298644
990,1570527354000000201 / 1570531687000000101,2025-12-29T12:56:38+00:00 / 2025-12-29T12:57:0...,2026-03-31,2035-08-15T00:00:00 / 2043-11-15T00:00:00,OIS_SWAP,9.51111 / 17.8861,10Y / 18Y,True,0.255556,3M,...,I,"[1570527354000000201, 1570531687000000101]",True,91282CNT4 / 912810TW8,10-Year / 20-Year,2025-08-15 / 2023-11-30,2035-08-15 / 2043-11-15,high,UTA,49656.500000
991,1570702409000000101,2025-12-29 12:56:44+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,N,[1570702409000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,93846.869312
1002,1570768102000000101,2025-12-29 13:08:52+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1570768102000000101],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,60691.324413
1023,1570769153000000601 / 1570770130000000201,2025-12-29T13:33:53+00:00 / 2025-12-29T13:33:5...,2026-03-31,2032-11-15T00:00:00 / 2052-11-15T00:00:00,OIS_SWAP,6.725 / 27.0167,7Y / 27Y,True,0.255556,3M,...,I,"[1570769153000000601, 1570770130000000201]",True,91282CFV8 / 912810TL2,10-Year / 30-Year,2022-11-15,2032-11-15 / 2052-11-15,high,TYA,39884.900000
1030,1570742278000001101,2025-12-29 13:40:38+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570742278000001101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,175.962880
1040,1570774051000000101,2025-12-29 13:42:46+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1570774051000000101],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,50444.737174
1056,1570772476000000501,2025-12-29 13:56:55+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1570772476000000501],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,102465.872385
1085,1570792823000001201 / 1570792827000001601,2025-12-29 14:04:28+00:00,2026-03-31,2032-11-15T00:00:00 / 2052-11-15T00:00:00,OIS_SWAP,6.725 / 27.0167,7Y / 27Y,True,0.255556,3M,...,I,"[1570792823000001201, 1570792827000001601]",True,91282CFV8 / 912810TL2,10-Year / 30-Year,2022-11-15,2032-11-15 / 2052-11-15,high,TYA,39884.900000
1099,1570824186000000501 / 1570825868000000801,2025-12-29T14:12:51+00:00 / 2025-12-29T14:12:5...,2026-03-31,2032-11-15T00:00:00 / 2035-08-15T00:00:00,OIS_SWAP,6.725 / 9.51111,7Y / 10Y,True,0.255556,3M,...,I,"[1570824186000000501, 1570825868000000801]",True,91282CFV8 / 91282CNT4,10-Year,2022-11-15 / 2025-08-15,2032-11-15 / 2035-08-15,high,TYA,49856.100000
1142,1570877289000000401,2025-12-29 14:51:54+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570877289000000401],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,9971.229864
1161,1570939161000000201,2025-12-29 15:09:18+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570939161000000201],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,134904.874636
1164,1570916630000000101,2025-12-29 15:10:19+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570916630000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,49856.149322
1167,1570905700000000801,2025-12-29 15:13:22+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1570905700000000801],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,252223.685872
1177,1570926289000000201,2025-12-29 15:18:42+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1570926289000000201],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,49656.538156
1187,1570923934000000801 / 1570923935000000901,2025-12-29 15:25:58+00:00,2026-03-31,2031-12-31T00:00:00 / 2032-11-15T00:00:00,OIS_SWAP,5.83611 / 6.725,6Y / 7Y,True,0.255556,3M,...,I,"[1570923935000000901, 1570923934000000801]",True,91282CMC2 / 91282CFV8,7-Year / 10-Year,2024-12-31 / 2022-11-15,2031-12-31 / 2032-11-15,high,TYA,103398.000000
1206,1570941562000000301,2025-12-29 15:26:00+00:00,2026-03-31,2043-11-15 00:00:00,OIS_SWAP,17.886111,18Y,True,0.255556,3M,...,N,[1570941562000000301],True,912810TW8,20-Year,2023-11-30,2043-11-15,high,UTA,99680.703563
1238,1571746453000000201,2025-12-29 15:57:09+00:00,2026-03-31,2043-11-15 00:00:00,OIS_SWAP,17.886111,18Y,True,0.255556,3M,...,I,[1571746453000000201],True,912810TW8,20-Year,2023-11-30,2043-11-15,high,UTA,99680.703563
1285,1570993333000000101,2025-12-29 16:19:06+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1570993333000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,252213.461277
1321,1571025895000000101,2025-12-29 16:39:16+00:00,2026-03-31,2043-11-15 00:00:00,OIS_SWAP,17.886111,18Y,True,0.255556,3M,...,I,[1571025895000000101],True,912810TW8,20-Year,2023-11-30,2043-11-15,high,UTA,99680.703563
1342,1571621874000000301,2025-12-29 17:07:30+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1571621874000000301],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,99712.298644
1347,1571876734000000701,2025-12-29 17:09:51+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1571876734000000701],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,99712.298644
1373,1572341160000000201 / 1572341159000000101,2025-12-29 17:28:19+00:00,2026-03-31,2032-11-15T00:00:00 / 2035-08-15T00:00:00,OIS_SWAP,6.725 / 9.51111,7Y / 10Y,True,0.255556,3M,...,I,"[1572341160000000201, 1572341159000000101]",True,91282CFV8 / 91282CNT4,10-Year,2022-11-15 / 2025-08-15,2032-11-15 / 2035-08-15,high,TYA,49856.100000
1391,1572027519000000301,2025-12-29 17:47:41+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,I,[1572027519000000301],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,NaN,149757.813486
1392,1572249436000000801,2025-12-29 17:50:57+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1572249436000000801],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,41058.005324
1395,1572194286000000301,2025-12-29 16:27:34+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1572194286000000301],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,252213.461277
1487,1572646988000000101,2025-12-29 18:58:47+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1572646988000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,99712.298644
1499,1572618332000000501,2025-12-29 19:08:46+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1572618332000000501],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,99712.298644
1501,1572625889000000101,2025-12-29 19:10:21+00:00,2026-03-31,2053-11-15 00:00:00,OIS_SWAP,28.036111,28Y,True,0.255556,3M,...,I,[1572625889000000101],True,912810TV0,30-Year,2023-11-15,2053-11-15,high,UBA,246270.890076
1534,1572760759000000101,2025-12-29 19:50:45+00:00,2026-03-31,2053-11-15 00:00:00,OIS_SWAP,28.036111,28Y,True,0.255556,3M,...,I,[1572760759000000101],True,912810TV0,30-Year,2023-11-15,2053-11-15,high,UBA,100150.161964
1573,1572991032000000101,2025-12-29 20:38:11+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,I,[1572991032000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,TYA,19942.459729
1574,1572988289000000301,2025-12-29 19:26:57+00:00,2026-03-31,2053-11-15 00:00:00,OIS_SWAP,28.036111,28Y,True,0.255556,3M,...,I,[1572988289000000301],True,912810TV0,30-Year,2023-11-15,2053-11-15,high,UBA,246270.890076
1600,1573630150000000401,2025-12-29 21:40:02+00:00,2026-03-31,2044-05-15 00:00:00,OIS_SWAP,18.391667,18Y,True,0.255556,3M,...,I,[1573630150000000401],True,912810UB2,20-Year,2024-05-31,2044-05-15,high,UTB,15416.505922

In [167]:
df.columns

Index(['trade_id', 'execution_timestamp', 'effective_date', 'expiration_date',
       'product_type', 'tenor_years', 'tenor_label', 'is_forward',
       'forward_start_years', 'forward_label', 'trade_label', 'notional',
       'notional_currency', 'fixed_rate', 'strike', 'estimated_pv01',
       'package_type', 'package_id', 'UPI Underlier Name',
       'Platform identifier', 'Cleared', 'package_legs',
       'matched_ust_maturity', 'ust_cusip', 'ust_oi', 'ust_issue_date',
       'swap_maturity_date', 'matched_ust_maturity_trade_confidence', 'risk'],
      dtype='object')

In [155]:
from SDRUtils.products.usd.sofr_swaps import flag_invoice_swaps

In [156]:
flag_invoice_swaps(df)

{'TU': {'delivery': (datetime.date(2026, 3, 2), datetime.date(2026, 3, 31)),
  'basket_pricers': [RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 1, 3), _maturity_date=datetime.date(2027, 12, 31), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.472, _meta_data={'record_date': datetime.date(2023, 1, 3), 'label': 'T 3 7/8 Dec 27', 'cusip': '91282CGC9', 'oi': '5-Year', 'auction_date': datetime.date(2022, 12, 28), 'issue_date': datetime.date(2023, 1, 3), 'maturity_date': datetime.date(2027, 12, 31), 'cpn': 3.875, 'rank': 34, 'timestamp': Timestamp('2025-12-29 19:26:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 1, 31), _maturity_date=datetime.date(2028, 1, 31), _cpn=3.5, _notional=None, _clean_price=None, _ytm=3.479, _meta_data={'record_date': datetime.date(2023, 1, 31), 'label': 'T 3 1/2 Jan 28', 'cusip': '91282CGH8', 'oi': '5-Year', 'auction_date': datetime.date(2023, 1, 25), 'issue_date': datetime.date(2023, 1, 31), 'maturity_date': datetime.date(2028, 1, 31), 'cpn': 3.5, 'rank': 33, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 2, 28), _maturity_date=datetime.date(2028, 2, 29), _cpn=4.0, _notional=None, _clean_price=None, _ytm=3.473, _meta_data={'record_date': datetime.date(2023, 2, 28), 'label': 'T 4 Feb 28', 'cusip': '91282CGP0', 'oi': '5-Year', 'auction_date': datetime.date(2023, 2, 22), 'issue_date': datetime.date(2023, 2, 28), 'maturity_date': datetime.date(2028, 2, 29), 'cpn': 4.0, 'rank': 32, 'timestamp': Timestamp('2025-12-29 20:51:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 3, 31), _maturity_date=datetime.date(2028, 3, 31), _cpn=3.625, _notional=None, _clean_price=None, _ytm=3.488, _meta_data={'record_date': datetime.date(2023, 3, 31), 'label': 'T 3 5/8 Mar 28', 'cusip': '91282CGT2', 'oi': '5-Year', 'auction_date': datetime.date(2023, 3, 28), 'issue_date': datetime.date(2023, 3, 31), 'maturity_date': datetime.date(2028, 3, 31), 'cpn': 3.625, 'rank': 31, 'timestamp': Timestamp('2025-12-29 20:24:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2024, 12, 16), _maturity_date=datetime.date(2027, 12, 15), _cpn=4.0, _notional=None, _clean_price=None, _ytm=3.467, _meta_data={'record_date': datetime.date(2024, 12, 16), 'label': 'T 4 Dec 27', 'cusip': '91282CMB4', 'oi': '3-Year', 'auction_date': datetime.date(2024, 12, 10), 'issue_date': datetime.date(2024, 12, 16), 'maturity_date': datetime.date(2027, 12, 15), 'cpn': 4.0, 'rank': 12, 'timestamp': Timestamp('2025-12-29 19:26:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 1, 15), _maturity_date=datetime.date(2028, 1, 15), _cpn=4.25, _notional=None, _clean_price=None, _ytm=3.482, _meta_data={'record_date': datetime.date(2025, 1, 15), 'label': 'T 4 1/4 Jan 28', 'cusip': '91282CMF5', 'oi': '3-Year', 'auction_date': datetime.date(2025, 1, 6), 'issue_date': datetime.date(2025, 1, 15), 'maturity_date': datetime.date(2028, 1, 15), 'cpn': 4.25, 'rank': 11, 'timestamp': Timestamp('2025-12-29 19:26:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 2, 18), _maturity_date=datetime.date(2028, 2, 15), _cpn=4.25, _notional=None, _clean_price=None, _ytm=3.476, _meta_data={'record_date': datetime.date(2025, 2, 18), 'label': 'T 4 1/4 Feb 28', 'cusip': '91282CMN8', 'oi': '3-Year', 'auction_date': datetime.date(2025, 2, 11), 'issue_date': datetime.date(2025, 2, 18), 'maturity_date': datetime.date(2028, 2, 15), 'cpn': 4.25, 'rank': 10, 'timestamp': Timestamp('2025-12-29 20:51:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 3, 17), _maturity_date=datetime.date(2028, 3, 15), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.48, _meta_data={'record_date': datetime.date(2025, 3, 17), 'label': 'T 3 7/8 Mar 28', 'cusip': '91282CMS7', 'oi': '3-Year', 'auction_date': datetime.date(2025, 3, 11), 'issue_date': datetime.date(2025, 3, 17), 'maturity_date': datetime.date(2028, 3, 15), 'cpn': 3.875, 'rank': 9, 'timestamp': Timestamp('2025-12-29 20:24:00+0000', tz='UTC')})],
  'conversion_factors': [0.9651,
   0.9571,
   0.9643,
   0.9559,
   0.9672,
   0.97,
   0.9687,
   0.9605],
  'contract_coupon': 6.0,
  'calc_mode': 'ust_short'},
 'FV': {'delivery': (datetime.date(2026, 3, 2), datetime.date(2026, 3, 31)),
  'basket_pricers': [RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 6, 2), _maturity_date=datetime.date(2030, 5, 31), _cpn=4.0, _notional=None, _clean_price=None, _ytm=3.633, _meta_data={'record_date': datetime.date(2025, 6, 2), 'label': 'T 4 May 30', 'cusip': '91282CNG2', 'oi': '5-Year', 'auction_date': datetime.date(2025, 5, 28), 'issue_date': datetime.date(2025, 6, 2), 'maturity_date': datetime.date(2030, 5, 31), 'cpn': 4.0, 'rank': 6, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 6, 30), _maturity_date=datetime.date(2030, 6, 30), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.645, _meta_data={'record_date': datetime.date(2025, 6, 30), 'label': 'T 3 7/8 Jun 30', 'cusip': '91282CNK3', 'oi': '5-Year', 'auction_date': datetime.date(2025, 6, 25), 'issue_date': datetime.date(2025, 6, 30), 'maturity_date': datetime.date(2030, 6, 30), 'cpn': 3.875, 'rank': 5, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 7, 31), _maturity_date=datetime.date(2030, 7, 31), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.647, _meta_data={'record_date': datetime.date(2025, 7, 31), 'label': 'T 3 7/8 Jul 30', 'cusip': '91282CNN7', 'oi': '5-Year', 'auction_date': datetime.date(2025, 7, 28), 'issue_date': datetime.date(2025, 7, 31), 'maturity_date': datetime.date(2030, 7, 31), 'cpn': 3.875, 'rank': 4, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 9, 2), _maturity_date=datetime.date(2030, 8, 31), _cpn=3.625, _notional=None, _clean_price=None, _ytm=3.657, _meta_data={'record_date': datetime.date(2025, 9, 2), 'label': 'T 3 5/8 Aug 30', 'cusip': '91282CNX5', 'oi': '5-Year', 'auction_date': datetime.date(2025, 8, 27), 'issue_date': datetime.date(2025, 9, 2), 'maturity_date': datetime.date(2030, 8, 31), 'cpn': 3.625, 'rank': 3, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 9, 30), _maturity_date=datetime.date(2030, 9, 30), _cpn=3.625, _notional=None, _clean_price=None, _ytm=3.662, _meta_data={'record_date': datetime.date(2025, 9, 30), 'label': 'T 3 5/8 Sep 30', 'cusip': '91282CPA3', 'oi': '5-Year', 'auction_date': datetime.date(2025, 9, 24), 'issue_date': datetime.date(2025, 9, 30), 'maturity_date': datetime.date(2030, 9, 30), 'cpn': 3.625, 'rank': 2, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 10, 31), _maturity_date=datetime.date(2030, 10, 31), _cpn=3.625, _notional=None, _clean_price=None, _ytm=3.67, _meta_data={'record_date': datetime.date(2025, 10, 31), 'label': 'T 3 5/8 Oct 30', 'cusip': '91282CPD7', 'oi': '5-Year', 'auction_date': datetime.date(2025, 10, 27), 'issue_date': datetime.date(2025, 10, 31), 'maturity_date': datetime.date(2030, 10, 31), 'cpn': 3.625, 'rank': 1, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 12, 1), _maturity_date=datetime.date(2030, 11, 30), _cpn=3.5, _notional=None, _clean_price=None, _ytm=3.672, _meta_data={'record_date': datetime.date(2025, 12, 1), 'label': 'T 3 1/2 Nov 30', 'cusip': '91282CPN5', 'oi': '5-Year', 'auction_date': datetime.date(2025, 11, 25), 'issue_date': datetime.date(2025, 12, 1), 'maturity_date': datetime.date(2030, 11, 30), 'cpn': 3.5, 'rank': 0, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')})],
  'conversion_factors': [0.9272, 0.9212, 0.9199, 0.909, 0.9075, 0.906, 0.8995],
  'contract_coupon': 6.0,
  'calc_mode': 'ust_short'},
 'TY': {'delivery': (datetime.date(2026, 3, 2), datetime.date(2026, 3, 31)),
  'basket_pricers': [RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2022, 11, 15), _maturity_date=datetime.date(2032, 11, 15), _cpn=4.125, _notional=None, _clean_price=None, _ytm=3.871, _meta_data={'record_date': datetime.date(2022, 11, 15), 'label': 'T 4 1/8 Nov 32', 'cusip': '91282CFV8', 'oi': '10-Year', 'auction_date': datetime.date(2022, 11, 9), 'issue_date': datetime.date(2022, 11, 15), 'maturity_date': datetime.date(2032, 11, 15), 'cpn': 4.125, 'rank': 12, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 2, 15), _maturity_date=datetime.date(2033, 2, 15), _cpn=3.5, _notional=None, _clean_price=None, _ytm=3.9, _meta_data={'record_date': datetime.date(2023, 2, 15), 'label': 'T 3 1/2 Feb 33', 'cusip': '91282CGM7', 'oi': '10-Year', 'auction_date': datetime.date(2023, 2, 8), 'issue_date': datetime.date(2023, 2, 15), 'maturity_date': datetime.date(2033, 2, 15), 'cpn': 3.5, 'rank': 11, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 5, 15), _maturity_date=datetime.date(2033, 5, 15), _cpn=3.375, _notional=None, _clean_price=None, _ytm=3.921, _meta_data={'record_date': datetime.date(2023, 5, 15), 'label': 'T 3 3/8 May 33', 'cusip': '91282CHC8', 'oi': '10-Year', 'auction_date': datetime.date(2023, 5, 10), 'issue_date': datetime.date(2023, 5, 15), 'maturity_date': datetime.date(2033, 5, 15), 'cpn': 3.375, 'rank': 10, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 8, 15), _maturity_date=datetime.date(2033, 8, 15), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.941, _meta_data={'record_date': datetime.date(2023, 8, 15), 'label': 'T 3 7/8 Aug 33', 'cusip': '91282CHT1', 'oi': '10-Year', 'auction_date': datetime.date(2023, 8, 9), 'issue_date': datetime.date(2023, 8, 15), 'maturity_date': datetime.date(2033, 8, 15), 'cpn': 3.875, 'rank': 9, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2023, 11, 15), _maturity_date=datetime.date(2033, 11, 15), _cpn=4.5, _notional=None, _clean_price=None, _ytm=3.953, _meta_data={'record_date': datetime.date(2023, 11, 15), 'label': 'T 4 1/2 Nov 33', 'cusip': '91282CJJ1', 'oi': '10-Year', 'auction_date': datetime.date(2023, 11, 8), 'issue_date': datetime.date(2023, 11, 15), 'maturity_date': datetime.date(2033, 11, 15), 'cpn': 4.5, 'rank': 8, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2024, 2, 15), _maturity_date=datetime.date(2034, 2, 15), _cpn=4.0, _notional=None, _clean_price=None, _ytm=3.981, _meta_data={'record_date': datetime.date(2024, 2, 15), 'label': 'T 4 Feb 34', 'cusip': '91282CJZ5', 'oi': '10-Year', 'auction_date': datetime.date(2024, 2, 7), 'issue_date': datetime.date(2024, 2, 15), 'maturity_date': datetime.date(2034, 2, 15), 'cpn': 4.0, 'rank': 7, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 9, 30), _maturity_date=datetime.date(2032, 9, 30), _cpn=3.875, _notional=None, _clean_price=None, _ytm=3.865, _meta_data={'record_date': datetime.date(2025, 9, 30), 'label': 'T 3 7/8 Sep 32', 'cusip': '91282CNZ0', 'oi': '7-Year', 'auction_date': datetime.date(2025, 9, 25), 'issue_date': datetime.date(2025, 9, 30), 'maturity_date': datetime.date(2032, 9, 30), 'cpn': 3.875, 'rank': 2, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 10, 31), _maturity_date=datetime.date(2032, 10, 31), _cpn=3.75, _notional=None, _clean_price=None, _ytm=3.873, _meta_data={'record_date': datetime.date(2025, 10, 31), 'label': 'T 3 3/4 Oct 32', 'cusip': '91282CPF2', 'oi': '7-Year', 'auction_date': datetime.date(2025, 10, 28), 'issue_date': datetime.date(2025, 10, 31), 'maturity_date': datetime.date(2032, 10, 31), 'cpn': 3.75, 'rank': 1, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 12, 1), _maturity_date=datetime.date(2032, 11, 30), _cpn=3.75, _notional=None, _clean_price=None, _ytm=3.879, _meta_data={'record_date': datetime.date(2025, 12, 1), 'label': 'T 3 3/4 Nov 32', 'cusip': '91282CPM7', 'oi': '7-Year', 'auction_date': datetime.date(2025, 11, 26), 'issue_date': datetime.date(2025, 12, 1), 'maturity_date': datetime.date(2032, 11, 30), 'cpn': 3.75, 'rank': 0, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')})],
  'conversion_factors': [0.9003,
   0.8628,
   0.8517,
   0.8765,
   0.9105,
   0.8774,
   0.887,
   0.8804,
   0.8804],
  'contract_coupon': 6.0,
  'calc_mode': 'ust_long'},
 'UXY': {'delivery': (datetime.date(2026, 3, 2), datetime.date(2026, 3, 31)),
  'basket_pricers': [RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 8, 15), _maturity_date=datetime.date(2035, 8, 15), _cpn=4.25, _notional=None, _clean_price=None, _ytm=4.095, _meta_data={'record_date': datetime.date(2025, 8, 15), 'label': 'T 4 1/4 Aug 35', 'cusip': '91282CNT4', 'oi': '10-Year', 'auction_date': datetime.date(2025, 8, 6), 'issue_date': datetime.date(2025, 8, 15), 'maturity_date': datetime.date(2035, 8, 15), 'cpn': 4.25, 'rank': 1, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2025, 11, 17), _maturity_date=datetime.date(2035, 11, 15), _cpn=4.0, _notional=None, _clean_price=None, _ytm=4.117, _meta_data={'record_date': datetime.date(2025, 11, 17), 'label': 'T 4 Nov 35', 'cusip': '91282CPJ4', 'oi': '10-Year', 'auction_date': datetime.date(2025, 11, 12), 'issue_date': datetime.date(2025, 11, 17), 'maturity_date': datetime.date(2035, 11, 15), 'cpn': 4.0, 'rank': 0, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')})],
  'conversion_factors': [0.8771, 0.8568],
  'contract_coupon': 6.0,
  'calc_mode': 'ust_long'},
 'US': {'delivery': (datetime.date(2026, 3, 2), datetime.date(2026, 3, 31)),
  'basket_pricers': [RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2011, 5, 16), _maturity_date=datetime.date(2041, 5, 15), _cpn=4.375, _notional=None, _clean_price=None, _ytm=4.563, _meta_data={'record_date': datetime.date(2011, 5, 16), 'label': 'T 4 3/8 May 41', 'cusip': '912810QQ4', 'oi': '30-Year', 'auction_date': datetime.date(2011, 5, 12), 'issue_date': datetime.date(2011, 5, 16), 'maturity_date': datetime.date(2041, 5, 15), 'cpn': 4.375, 'rank': 58, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2011, 8, 15), _maturity_date=datetime.date(2041, 8, 15), _cpn=3.75, _notional=None, _clean_price=None, _ytm=4.601, _meta_data={'record_date': datetime.date(2011, 8, 15), 'label': 'T 3 3/4 Aug 41', 'cusip': '912810QS0', 'oi': '30-Year', 'auction_date': datetime.date(2011, 8, 11), 'issue_date': datetime.date(2011, 8, 15), 'maturity_date': datetime.date(2041, 8, 15), 'cpn': 3.75, 'rank': 57, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2011, 11, 15), _maturity_date=datetime.date(2041, 11, 15), _cpn=3.125, _notional=None, _clean_price=None, _ytm=4.64, _meta_data={'record_date': datetime.date(2011, 11, 15), 'label': 'T 3 1/8 Nov 41', 'cusip': '912810QT8', 'oi': '30-Year', 'auction_date': datetime.date(2011, 11, 10), 'issue_date': datetime.date(2011, 11, 15), 'maturity_date': datetime.date(2041, 11, 15), 'cpn': 3.125, 'rank': 56, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2012, 2, 15), _maturity_date=datetime.date(2042, 2, 15), _cpn=3.125, _notional=None, _clean_price=None, _ytm=4.658, _meta_data={'record_date': datetime.date(2012, 2, 15), 'label': 'T 3 1/8 Feb 42', 'cusip': '912810QU5', 'oi': '30-Year', 'auction_date': datetime.date(2012, 2, 9), 'issue_date': datetime.date(2012, 2, 15), 'maturity_date': datetime.date(2042, 2, 15), 'cpn': 3.125, 'rank': 55, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2012, 5, 15), _maturity_date=datetime.date(2042, 5, 15), _cpn=3.0, _notional=None, _clean_price=None, _ytm=4.678, _meta_data={'record_date': datetime.date(2012, 5, 15), 'label': 'T 3 May 42', 'cusip': '912810QW1', 'oi': '30-Year', 'auction_date': datetime.date(2012, 5, 10), 'issue_date': datetime.date(2012, 5, 15), 'maturity_date': datetime.date(2042, 5, 15), 'cpn': 3.0, 'rank': 54, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2012, 8, 15), _maturity_date=datetime.date(2042, 8, 15), _cpn=2.75, _notional=None, _clean_price=None, _ytm=4.701, _meta_data={'record_date': datetime.date(2012, 8, 15), 'label': 'T 2 3/4 Aug 42', 'cusip': '912810QX9', 'oi': '30-Year', 'auction_date': datetime.date(2012, 8, 9), 'issue_date': datetime.date(2012, 8, 15), 'maturity_date': datetime.date(2042, 8, 15), 'cpn': 2.75, 'rank': 53, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),
   RLFixedRateBondPricer(_rl_frb_id='USTS', _reference_date=datetime.date(2025, 12, 29), _issue_date=datetime.date(2012, 11, 15), _maturity_date=datetime.date(2042, 11, 15), _cpn=2.75, _notional=None, _clean_price=None, _ytm=4.72, _meta_data={'record_date': datetime.date(2012, 11, 15), 'label': 'T 2 3/4 Nov 42', 'cusip': '912810QY7', 'oi': '30-Year', 'auction_date': datetime.date(2012, 11, 8), 'issue_date': datetime.date(2012, 11, 15), 'maturity_date': datetime.date(2042, 11, 15), 'cpn': 2.75, 'rank': 52, 'timestamp': Timestamp('2025-12-29 20:00:00+0000', tz='UTC')}),

In [ ]:
df.to_csv("sdr_formatted_usd_rates.csv", index=False)

In [152]:
# .head(5).to_dict(orient="records")
df[df["matched_ust_maturity_trade_confidence"] == "high"].head(25)

,trade_id,execution_timestamp,effective_date,expiration_date,product_type,tenor_years,tenor_label,is_forward,forward_start_years,forward_label,...,Platform identifier,Cleared,package_legs,matched_ust_maturity,ust_cusip,ust_oi,ust_issue_date,swap_maturity_date,matched_ust_maturity_trade_confidence,risk
963,1570211851000000101,2025-12-29 12:12:04+00:00,2025-12-31,2055-11-15 00:00:00,OIS_SWAP,30.308333,30Y,False,0.005556,spot,...,BILT,I,[1570211851000000101],True,912810UP1,30-Year,2025-11-17,2055-11-15,high,25876.304266
970,1570367247000000601,2025-12-29 12:35:27+00:00,2025-12-31,2027-06-30 00:00:00,OIS_SWAP,1.516667,18M,False,0.005556,spot,...,BBSF,I,[1570367247000000601],True,91282CNL1,2-Year,2025-06-30,2027-06-30,high,2478.871765
971,1570377103000000101,2025-12-29 12:37:08+00:00,2025-12-31,2028-06-30 00:00:00,OIS_SWAP,2.533333,3Y,False,0.005556,spot,...,BMTF,I,[1570377103000000101],True,91282CHK0,5-Year,2023-06-30,2028-06-30,high,5028.016796
974,1570380985000000401,2025-12-29 12:38:22+00:00,2026-03-31,2026-12-31 00:00:00,OIS_SWAP,0.763889,9M,True,0.255556,3M,...,TWSF,I,[1570380985000000401],True,91282CME8,2-Year,2024-12-31,2026-12-31,high,5533.409236
978,1570476216000000301,2025-12-29 12:43:06+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,BILT,I,[1570476216000000301],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,25221.346128
982,1570527359000000301,2025-12-29 12:45:25+00:00,2026-03-31,2032-11-30 00:00:00,OIS_SWAP,6.766667,7Y,True,0.255556,3M,...,BILT,I,[1570527359000000301],True,91282CPM7,7-Year,2025-12-01,2032-11-30,high,100245.298930
984,1570638065000001001,2025-12-29 12:54:12+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,BILT,I,[1570638065000001001],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,99712.298644
988,1570728645000000101,2025-12-29 12:55:37+00:00,2025-12-31,2027-03-15 00:00:00,OIS_SWAP,1.219444,IMM_H2027,False,0.005556,spot,...,XXXX,I,[1570728645000000101],True,91282CKE0,3-Year,2024-03-15,2027-03-15,high,117.733381
990,1570527354000000201 / 1570531687000000101,2025-12-29T12:56:38+00:00 / 2025-12-29T12:57:0...,2026-03-31,2035-08-15T00:00:00 / 2043-11-15T00:00:00,OIS_SWAP,9.51111 / 17.8861,10Y / 18Y,True,0.255556,3M,...,BILT,I,"[1570527354000000201, 1570531687000000101]",True,91282CNT4 / 912810TW8,10-Year / 20-Year,2025-08-15 / 2023-11-30,2035-08-15 / 2043-11-15,high,49656.500000
991,1570702409000000101,2025-12-29 12:56:44+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,BILT,N,[1570702409000000101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,93846.869312
1000,1570615218000000401 / 1570619361000000401,2025-12-29T13:07:18+00:00 / 2025-12-29T13:07:3...,2026-03-18,2028-03-15T00:00:00 / 2029-03-21T00:00:00,OIS_SWAP,2.02222 / 3.05278,IMM_H2028 / IMM_H2029,True,0.219444,IMM_H2026,...,BBSF,I,"[1570615218000000401, 1570619361000000401]",1 / 0,91282CMS7,3-Year,2025-03-17,2028-03-15 / 2029-03-21,high,28662.400000
1002,1570768102000000101,2025-12-29 13:08:52+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,BILT,I,[1570768102000000101],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,60691.324413
1006,1570697018000001101,2025-12-29 13:10:53+00:00,2026-04-03,2030-05-31 00:00:00,OIS_SWAP,4.219444,4Y,True,0.263889,3M,...,BILT,I,[1570697018000001101],True,91282CNG2,5-Year,2025-06-02,2030-05-31,high,49841.968027
1014,1570735237000000201,2025-12-29 13:24:34+00:00,2026-04-03,2027-12-15 00:00:00,OIS_SWAP,1.725,IMM_Z2027,True,0.263889,3M,...,BILT,I,[1570735237000000201],True,91282CMB4,3-Year,2024-12-16,2027-12-15,high,97823.909112
1023,1570769153000000601 / 1570770130000000201,2025-12-29T13:33:53+00:00 / 2025-12-29T13:33:5...,2026-03-31,2032-11-15T00:00:00 / 2052-11-15T00:00:00,OIS_SWAP,6.725 / 27.0167,7Y / 27Y,True,0.255556,3M,...,BILT,I,"[1570769153000000601, 1570770130000000201]",True,91282CFV8 / 912810TL2,10-Year / 30-Year,2022-11-15,2032-11-15 / 2052-11-15,high,39884.900000
1030,1570742278000001101,2025-12-29 13:40:38+00:00,2026-03-31,2032-11-15 00:00:00,OIS_SWAP,6.725,7Y,True,0.255556,3M,...,BBSF,I,[1570742278000001101],True,91282CFV8,10-Year,2022-11-15,2032-11-15,high,175.962880
1033,1570748322000000301,2025-12-29 13:42:34+00:00,2026-04-03,2027-12-15 00:00:00,OIS_SWAP,1.725,IMM_Z2027,True,0.263889,3M,...,BILT,I,[1570748322000000301],True,91282CMB4,3-Year,2024-12-16,2027-12-15,high,97823.909112
1039,1570769152000000501,2025-12-29 13:46:02+00:00,2025-12-31,2027-05-31 00:00:00,OIS_SWAP,1.425,1Y,False,0.005556,spot,...,BILT,I,[1570769152000000501],True,91282CNE7,2-Year,2025-06-02,2027-05-31,high,20577.919761
1040,1570774051000000101,2025-12-29 13:42:46+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,BILT,I,[1570774051000000101],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,50444.737174
1053,1570808768000000101,2025-12-29 13:56:03+00:00,2025-07-31,2035-05-15 00:00:00,OIS_SWAP,9.930556,10Y,False,-0.419444,spot,...,BILT,I,[1570808768000000101],True,91282CNC1,10-Year,2025-05-15,2035-05-15,high,15904.118001
1056,1570772476000000501,2025-12-29 13:56:55+00:00,2026-03-31,2035-08-15 00:00:00,OIS_SWAP,9.511111,10Y,True,0.255556,3M,...,BILT,I,[1570772476000000501],True,91282CNT4,10-Year,2025-08-15,2035-08-15,high,102465.872385
1059,1570776534000000701,2025-12-29 13:59:04+00:00,2025-12-31,2055-11-15 00:00:00,OIS_SWAP,30.308333,30Y,False,0.005556,spot,...,BILT,I,[1570776534000000701],True,912810UP1,30-Year,2025-11-17,2055-11-15,high,207010.434125
1085,1570792823000001201 / 1570792827000001601,2025-12-29 14:04:28+00:00,2026-03-31,2032-11-15T00:00:00 / 2052-11-15T00:00:00,OIS_SWAP,6.725 / 27.0167,7Y / 27Y,True,0.255556,3M,...,TREU,I,"[1570792823000001201, 1570792827000001601]",True,91282CFV8 / 912810TL2,10-Year / 30-Year,2022-11-15,2032-11-15 / 2052-11-15,high,39884.900000
1089,1570864802000000101,2025-12-29 14:07:43+00:00,2025-12-12,2030-11-30 00:00:00,OIS_SWAP,5.036111,5Y,False,-0.047222,spot,...,BILT,I,[1570864802000000101],True,91282CPN5,5-Year,2025-12-01,2030-11-30,high,5025.421355
1090,1570864804000000301,2025-12-29 14:07:43+00:00,2025-12-08,2030-11-30 00:00:00,OIS_SWAP,5.047222,5Y,False,-0.058333,spot,...,BILT,I,[1570864804000000301],True,91282CPN5,5-Year,2025-12-01,2030-11-30,high,25186.301605

In [93]:
import numpy as np
np.arange(1, 31, dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])

In [81]:
from tvDatafeed import TvDatafeed, Interval

# tv = TvDatafeed("yieldcurvemonkey", "Football2203123@123")
tv = TvDatafeed()
df = tv.get_hist(symbol="912810UA4", exchange="OTCB", interval=Interval.in_1_minute, n_bars=1, extended_session=True)

WARNING	Task(Task-3) tvDatafeed.main:main.py:__init__()- you are using nologin method, data you access may be limited

In [84]:
df["close"]

datetime
2025-12-31 07:49:00    96.7031
Name: close, dtype: float64

In [32]:
df["trade_label"].value_counts().head(50)

trade_label
spot 10Y                                     131
spot 30Y                                      88
spot 5Y                                       84
spot 2Y                                       54
spot 3Y                                       51
IMM_H2026 IMM_H2031                           41
IMM_H2026 IMM_H2036                           36
spot 20Y                                      28
IMM_H2026 IMM_H2056                           27
spot 1Y                                       24
spot 7Y                                       23
IMM_H2026 IMM_H2028                           19
spot 1M                                       19
spot 3M                                       15
spot 4M                                       14
IMM_H2026 IMM_H2033                           13
spot 4Y                                       13
spot 2M                                       12
spot 6M                                       11
spot 6Y                                       11
IMM_Z2025 IMM_Z2030                           10
IMM_H2026 IMM_H2029                            9
3M 4Y                                          9
3M 18Y                                         9
IMM_H2026 IMM_H2029 / IMM_H2026 IMM_H2031      8
spot 9Y                                        7
spot 9M                                        7
spot 12Y                                       6
spot 15Y                                       6
spot 5M                                        6
5Y 5Y                                          6
spot 18M                                       6
IMM_Z2025 IMM_Z2055                            5
10Y / 30Y                                      5
spot IMM_H2026                                 4
2Y 23Y                                         4
2M 4Y                                          4
2M IMM_Z2027                                   4
IMM_Z2025 IMM_Z2028                            4
3M 10Y                                         4
IMM_Z2025 IMM_Z2035                            4
1W 1Y                                          4
IMM_M2026 IMM_M2041                            4
1W 3W                                          4
spot 25Y                                       4
spot 11Y                                       3
IMM_H2026 IMM_H2041                            3
1M 5Y                                          3
9Y IMM_H2045                                   3
spot 7M                                        3
Name: count, dtype: int64

In [17]:
df["estimated_pv01"]

0       50205.509059
1       50205.509059
2       29150.839208
3        4897.953618
4        8281.877471
            ...
1806     4014.907599
1807     2481.177386
1808    100055.04316
1809    99566.158534
1810    31438.779832
Name: estimated_pv01, Length: 1811, dtype: object

In [34]:
with_pkg_df.tail(1).to_dict(orient="records")

[{'trade_id': 1574395035000000101,
  'execution_timestamp': Timestamp('2025-12-30 00:32:12+0000', tz='UTC'),
  'effective_date': Timestamp('2026-04-03 00:00:00'),
  'expiration_date': Timestamp('2030-05-31 00:00:00'),
  'product_type': 'OIS_SWAP',
  'tenor_years': 4.219444444444444,
  'tenor_label': '4Y',
  'is_forward': True,
  'forward_start_years': 0.2611111111111111,
  'forward_label': '3M',
  'trade_label': '3M 4Y',
  'notional': 82000000.0,
  'notional_currency': 'USD',
  'fixed_rate': 0.033477,
  'strike': nan,
  'estimated_pv01': 31438.779832216656,
  'package_type': 'SPREADOVER',
  'package_id': 'SPREADOVER_1574395035000000101',
  'package_legs': [1574395035000000101],
  'matched_ust_maturity': True,
  'ust_cusip': '91282CNG2',
  'ust_oi': '5-Year',
  'ust_issue_date': datetime.date(2025, 6, 2),
  'swap_maturity_date': datetime.date(2030, 5, 31)}]

In [37]:
# with_pkg_df["estimated_pv01"].sort_values(key=lambda x: float(str(x).split("/")[0]) if type(x) == str else float(x))

# with_pkg_df["pv01_clean"] = with_pkg_df["estimated_pv01"].apply(lambda x: float(str(x).split("/")[0]) if type(x) == str else float(x))
# with_pkg_df.sort_values(by="pv01_clean", ascending=False).head(10)