In [15]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import sys
sys.path.append("../")

import nest_asyncio
nest_asyncio.apply()

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "vscode"            

import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.dates as mdates
plt.style.use('seaborn-v0_8-dark')
params = {'legend.fontsize': 'x-large',
        'figure.figsize': (16, 9),
        'axes.labelsize': 'x-large',
        'axes.titlesize':'x-large',
        'xtick.labelsize':'x-large',
        'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)

import pandas as pd
import numpy as np
import QuantLib as ql
import rateslib as rl

import datetime
import pytz
NY_tz = pytz.timezone("America/New_York") 
CHI_tz = pytz.timezone("America/Chicago") 
UTC_tz = pytz.timezone("UTC")

import warnings
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
cache_path = r"C:\Users\chris\clee\project-oasis\private\sdranalytics\.cache"
start = NY_tz.localize(datetime.datetime(2025, 12, 29, 0, 0))
end = NY_tz.localize(datetime.datetime(2025, 12, 29, 23, 59))

from SDRUtils.data.builder import SDRDataBuilder
sdr = SDRDataBuilder(cache_path=cache_path, show_tqdm=True)
df = sdr.grab_sdr_trades(
	start_timestamp=start,
	end_timestamp=end,
	agency="CFTC",
	asset_class="RATES",
)
df

CACHE HIT...: 100%|██████████| 2/2 [00:00<00:00, 48.45it/s]
MERGING SLICES...: 100%|██████████| 2/2 [00:00<00:00, 182.09it/s]

,Dissemination Identifier,Original Dissemination Identifier,Action type,Event type,Event timestamp,Amendment indicator,Asset Class,Product name,Cleared,Mandatory clearing indicator,...,Package transaction price currency,Package transaction price notation,Package transaction spread,Package transaction spread currency,Package transaction spread notation,Physical delivery location-Leg 1,Delivery Type,Unique Product Identifier,UPI FISN,UPI Underlier Name
0,1563618455000000301,NaN,NEWT,TRAD,2025-12-29 05:01:14+00:00,None,IR,None,I,True,...,,NaN,,,NaN,None,None,QZF08M5TR8H3,NA/Swap OIS JPY,JPY-TONA-OIS Compound
1,1563618456000000401,1.563618e+18,MODI,TRAD,2025-12-29 05:01:16+00:00,True,IR,None,I,True,...,,NaN,,,NaN,None,None,QZF08M5TR8H3,NA/Swap OIS JPY,JPY-TONA-OIS Compound
2,1563618457000000501,1.563618e+18,MODI,TRAD,2025-12-29 05:01:19+00:00,False,IR,None,I,True,...,,NaN,,,NaN,None,None,QZF08M5TR8H3,NA/Swap OIS JPY,JPY-TONA-OIS Compound
3,1563618458000000601,1.563618e+18,MODI,TRAD,2025-12-29 05:01:23+00:00,False,IR,None,I,True,...,,NaN,,,NaN,None,None,QZF08M5TR8H3,NA/Swap OIS JPY,JPY-TONA-OIS Compound
4,1563618910000000101,1.563616e+18,CORR,,2025-12-29 05:01:29+00:00,None,IR,None,I,True,...,,3.0,,,NaN,None,None,QZF08M5TR8H3,NA/Swap OIS JPY,JPY-TONA-OIS Compound
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11173,1575253883000000101,NaN,NEWT,TRAD,2025-12-30 04:56:51+00:00,None,IR,None,N,False,...,,NaN,,,NaN,None,None,QZ4HTNF4RVB5,NA/Swap Flt Flt AUD USD,AUD-BBSW vs USD-SOFR-OIS Compound
11174,1575167371000000101,NaN,NEWT,TRAD,2025-12-30 04:57:00+00:00,None,IR,None,I,False,...,,NaN,,,NaN,None,None,QZXF4PFZSLP7,NA/Swap OIS INR,INR-MIBOR-OIS Compound
11175,1575159075000000101,NaN,NEWT,TRAD,2025-12-30 04:57:10+00:00,None,IR,None,I,True,...,,NaN,,,NaN,None,None,QZV61TRS4HD9,NA/Swap OIS JPY,JPY-TONA-OIS-COMPOUND
11176,1575168481000000101,NaN,NEWT,TRAD,2025-12-30 04:57:34+00:00,None,IR,None,I,False,...,,NaN,,,NaN,None,None,QZ26BPG38C1K,NA/Swap Fxd Flt KRW,KRW-CD 91D
11177,1575161059000000101,NaN,NEWT,TRAD,2025-12-30 04:58:09+00:00,None,IR,None,I,False,...,,NaN,,,NaN,None,None,QZ26BPG38C1K,NA/Swap Fxd Flt KRW,KRW-CD 91D

In [17]:
# from SDRUtils.products.usd.sofr_swaps import USD_SOFR_SwapProduct 
# USD_SOFR_SwapProduct().build_classification_dataframe(start=start, end=end, cache_path=cache_path)

from SDRUtils.products.usd.usd_swaptions import USD_Swaptions
sdf = USD_Swaptions().build_classification_dataframe(start=start, end=end, cache_path=cache_path)
sdf.head(50)

CACHE HIT...: 100%|██████████| 2/2 [00:00<00:00, 51.29it/s]
MERGING SLICES...: 100%|██████████| 2/2 [00:00<00:00, 181.37it/s]
Classifying Trades: 100%|██████████| 392/392 [00:00<00:00, 1783.79trade/s]

,event_action,trade_id,execution_timestamp,effective_date,expiration_date,product_type,trade_label,notional,notional_currency,is_notional_capped,...,upi_underlier_name,unique_product_identifier,platform_identifier,cleared,package_indicator,package_transaction_price,option_premium_amount,package_confidence,package_reason,package_legs_count
0,NEWT-TRAD,1568561409000000201,2025-12-29 09:17:55+00:00,2025-12-29,2026-12-29,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 1Y6Y CHOOSER...,1.000000e+07,USD,False,...,NA/Swap OIS USD,QZJBL64PCV75,XOFF,N,False,,"164,810",NaN,None,None
1,NEWT-NOVA,1568080997000000501,2025-12-29 09:19:10+00:00,2025-12-18,2026-08-21,SWAPTION_PAYER,USD-SOFR-OIS Compound 1Y CONSTANT 8M1Y PAYER E...,1.000000e+09,USD,False,...,NA/Swap OIS USD,QZZLNQ2D4JQT,BILT,N,False,,0,NaN,None,None
2,NEWT-TRAD,1570737966000000101,2025-12-29 13:05:00+00:00,2025-12-29,2026-02-27,SWAPTION_RECEIVER,USD-SOFR-COMPOUND 1D CONSTANT 2M10Y RECEIVER E...,2.000000e+08,USD,False,...,NA/Swap Fxd Flt USD,QZXZSN00ZVCG,BILT,N,False,,0,NaN,None,None
3,NEWT-TRAD,1570736565000000601,2025-12-29 13:05:00+00:00,2025-12-29,2026-02-27,SWAPTION_RECEIVER,USD-SOFR-COMPOUND 1D CONSTANT 2M10Y RECEIVER E...,2.000000e+08,USD,False,...,NA/Swap Fxd Flt USD,QZXZSN00ZVCG,BILT,N,False,,"3,610,000",NaN,None,None
4,NEWT-TRAD,1570700284000000301,2025-12-29 13:22:05+00:00,2025-12-29,2026-11-20,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 11M10Y RECEI...,5.000000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,"2,447,500",NaN,None,None
5,NEWT-TRAD,1570700285000000401,2025-12-29 13:22:05+00:00,2025-12-29,2026-11-20,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 11M10Y RECEI...,5.000000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,0,NaN,None,None
6,NEWT-TRAD,1570700287000000601,2025-12-29 13:22:06+00:00,2025-12-29,2026-08-19,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 8M10Y CHOOSE...,4.500000e+07,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,BILT,N,False,,0,NaN,None,None
7,NEWT-TRAD,1570700286000000501,2025-12-29 13:22:06+00:00,2025-12-29,2026-08-19,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 8M10Y CHOOSE...,4.500000e+07,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,BILT,N,False,,"1,831,500",NaN,None,None
8,TERM-ETRM,1570736561000000201,2025-12-29 13:36:16+00:00,2025-12-29,2026-11-20,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 11M10Y RECEI...,5.000000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,,N,False,,0,NaN,None,None
9,TERM-ETRM,1570736562000000301,2025-12-29 13:36:17+00:00,2025-12-29,2026-11-20,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 11M10Y RECEI...,5.000000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,,N,False,,0,NaN,None,None
10,TERM-ETRM,1570753364000000601,2025-12-29 13:45:49+00:00,2025-12-29,2026-08-19,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 8M10Y CHOOSE...,4.500000e+07,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,,N,False,,0,NaN,None,None
11,TERM-ETRM,1570753365000000701,2025-12-29 13:45:50+00:00,2025-12-29,2026-08-19,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 8M10Y CHOOSE...,4.500000e+07,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,,N,False,,0,NaN,None,None
12,NEWT-TRAD,1570783118000001101,2025-12-29 13:52:41+00:00,2025-12-29,2027-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 2Y5Y RECEIVE...,2.500000e+08,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,0,NaN,None,None
13,NEWT-TRAD,1570783119000001201,2025-12-29 13:52:41+00:00,2025-12-29,2027-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 2Y5Y RECEIVE...,2.500000e+08,USD,False,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,"10,487,500",NaN,None,None
14,NEWT-TRAD,1570783121000001401,2025-12-29 13:52:52+00:00,2025-12-29,2028-12-28,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3Y1Y RECEIVE...,6.500000e+08,USD,True,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,0,NaN,None,None
15,NEWT-TRAD,1570783120000001301,2025-12-29 13:52:52+00:00,2025-12-29,2028-12-28,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3Y1Y RECEIVE...,6.500000e+08,USD,True,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,False,,"7,540,000",NaN,None,None
16,NEWT-TRAD,1570840544000000701,2025-12-29 14:13:57+00:00,2025-12-29,2026-12-29,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1Y CONSTANT 1Y10Y CHOOSE...,1.500000e+08,USD,False,...,NA/Swap OIS USD,QZHQPRHC3S7T,BILT,N,False,,"7,725,000",NaN,None,None
17,NEWT-TRAD,1570838918000000301,2025-12-29 14:13:57+00:00,2025-12-29,2027-12-29,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1Y CONSTANT 2Y2Y CHOOSER...,5.000000e+08,USD,False,...,NA/Swap OIS USD,QZHQPRHC3S7T,BILT,N,False,,"9,100,000",NaN,None,None
18,NEWT-TRAD,1570828016000000501,2025-12-29 14:19:07+00:00,2025-12-29,2026-01-29,SWAPTION_CHOOSER,USD-SOFR-COMPOUND 1D CONSTANT 1M10Y CHOOSER EU...,1.000000e+20,,False,...,NA/Swap OIS USD,QZKDXXXPW3X3,BILT,N,False,,0,NaN,None,None
19,NEWT-TRAD,1570828017000000601,2025-12-29 14:19:07+00:00,2025-12-29,2026-01-29,SWAPTION_CHOOSER,USD-SOFR-COMPOUND 1D CONSTANT 1M10Y CHOOSER EU...,1.000000e+20,,False,...,NA/Swap OIS USD,QZKDXXXPW3X3,BILT,N,True,"1,537,500","1,537,500",NaN,None,None
20,NEWT-TRAD,1570863724000000501,2025-12-29 14:28:04+00:00,2025-12-29,2026-03-30,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 3M4Y PAYER EURO ...,2.000000e+06,USD,False,...,NA/Swap Fxd Flt USD,QZP4BJ4T4W9T,BILT,N,False,,"8,699.9913",NaN,None,None
21,NEWT-TRAD,1570863725000000601,2025-12-29 14:28:07+00:00,2025-12-29,2026-03-30,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 3M4Y PAYER EURO ...,8.000000e+06,USD,False,...,NA/Swap Fxd Flt USD,QZP4BJ4T4W9T,BILT,N,False,,"34,799.9652",NaN,None,None
22,NEWT-TRAD,1570863720000000101,2025-12-29 14:36:44+00:00,2025-12-29,2026-02-20,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 2M10Y CHOOSE...,6.300000e+07,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,BILT,N,True,9.9999999999,"1,089,900",NaN,None,None
23,NEWT-TRAD,1570875069000000601,2025-12-29 14:38:41+00:00,2025-12-29,2035-01-02,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1Y CONSTANT 9Y2M15Y CHOO...,3.000000e+07,USD,False,...,NA/Swap OIS USD,QZHQPRHC3S7T,BILT,N,False,,"5,808,000",NaN,None,None
24,NEWT-TRAD,1570875070000000701,2025-12-29 14:38:41+00:00,2025-12-29,2032-05-24,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1Y CONSTANT 6Y6M10Y CHOO...,3.000000e+07,USD,False,...,NA/Swap OIS USD,QZHQPRHC3S7T,BILT,N,False,,"3,915,000",NaN,None,None
25,CORR-,1570894735000000101,2025-12-29 15:08:14+00:00,2025-12-15,2028-12-12,SWAPTION_RECEIVER,USD-SOFR CME Term 1M ACCRETING 3Y0D RECEIVER B...,8.400000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZTRSNZTX0F0,XXXX,N,False,,0,NaN,None,None
26,TERM-ETRM,1570906123000000101,2025-12-29 15:12:29+00:00,2024-09-20,2029-07-30,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 4Y11M1M PAYER BE...,1.000000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7XW3KWNFQ0,XXXX,N,False,,0,NaN,None,None
27,NEWT-TRAD,1570950502000000201,2025-12-29 15:36:21+00:00,2025-12-29,2026-01-29,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1Y CONSTANT 1M10Y CHOOSE...,5.800000e+07,USD,False,...,NA/Swap OIS USD,QZHQPRHC3S7T,BILT,N,False,,"693,100.478",NaN,None,None
28,NEWT-TRAD,1571020095000000101,2025-12-29 15:55:02+00:00,2025-12-29,2026-01-29,SWAPTION_RECEIVER,USD-SOFR-COMPOUND 1D CONSTANT 1M10Y RECEIVER E...,3.500000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZXZSN00ZVCG,BILT,N,False,,"23,625",NaN,None,None
29,NEWT-TRAD,1571020100000000601,2025-12-29 15:55:26+00:00,2025-12-29,2026-01-29,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 1M10Y PAYER EURO...,3.500000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZXSN072GFF3,BILT,N,False,,"23,625",NaN,None,None
30,TERM-EXER,1570966804000000901,2025-12-29 16:00:25+00:00,2021-09-29,2025-12-29,SWAPTION_CHOOSER,USD-SOFR 3M CONSTANT 4Y4M36Y CHOOSER EURO VANI...,2.500000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZVQ21ZLNJ5C,BILT,N,False,,0,NaN,None,None
31,TERM-EXER,1570979154000000501,2025-12-29 16:00:27+00:00,2025-10-28,2025-12-29,SWAPTION_PAYER,USD-SOFR-OIS Compound 1D CONSTANT 2M10Y PAYER ...,2.500000e+08,USD,True,...,NA/Swap OIS USD,QZZGWPNBF5R3,BILT,N,False,,0,NaN,None,None
32,TERM-EXER,1570966806000001101,2025-12-29 16:00:29+00:00,2025-11-20,2025-12-29,SWAPTION_PAYER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y PAYER ...,2.500000e+08,USD,True,...,NA/Swap OIS USD,QZZGWPNBF5R3,BILT,N,False,,"34,375",NaN,None,None
33,TERM-ETRM,1570971919000001001,2025-12-29 16:04:25+00:00,2025-11-04,2026-02-02,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 3M2Y CHOOSER...,5.000000e+08,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,BILT,N,True,,0,NaN,None,None
34,TERM-EXER,1571021126000000301,2025-12-29 16:17:57+00:00,2025-12-26,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT spot30Y RECE...,1.300000e+08,USD,False,...,NA/Swap OIS USD,QZNLQ8T0N0SX,BILT,N,False,,0,NaN,None,None
35,MODI-TRAD,1570991358000000101,2025-12-29 16:18:01+00:00,2025-12-29,2028-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3Y1M1Y RECEI...,6.500000e+08,USD,True,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,True,"12,500","7,540,000",NaN,None,None
36,MODI-TRAD,1570991359000000201,2025-12-29 16:18:02+00:00,2025-12-29,2028-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3Y1M1Y RECEI...,6.500000e+08,USD,True,...,NA/Swap Fxd Flt USD,QZ7B7ZPS1LS5,BILT,N,True,"12,500",0,NaN,None,None
37,NEWT-TRAD,1571011915000002001,2025-12-29 16:27:12+00:00,2025-12-29,2030-09-23,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 4Y10M3M PAYER BE...,6.000000e+06,USD,False,...,NA/Swap Fxd Flt USD,QZ7XW3KWNFQ0,XXXX,N,False,,0,NaN,None,None
38,NEWT-TRAD,1571013274000000201,2025-12-29 16:28:42+00:00,2025-12-29,2027-07-12,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 1Y7M4Y PAYER BER...,1.100000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7XW3KWNFQ0,XXXX,N,False,,0,NaN,None,None
39,TERM-EXER,1571020096000000201,2025-12-29 16:36:48+00:00,2025-12-15,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 2W30Y RECEIV...,1.300000e+08,USD,False,...,NA/Swap OIS USD,QZNLQ8T0N0SX,BILT,N,False,,"1,072,500",NaN,None,None
40,NEWT-TRAD,1571108206000000101,2025-12-29 16:47:27+00:00,2025-12-29,2026-03-30,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3M5Y RECEIVE...,3.000000e+08,USD,False,...,NA/Swap OIS USD,QZNLQ8T0N0SX,BILT,N,False,,"2,017,500",NaN,None,None
41,NEWT-TRAD,1571154356000000101,2025-12-29 16:55:22+00:00,2025-12-29,2026-03-30,SWAPTION_PAYER,USD-SOFR-OIS Compound 1D CONSTANT 3M7Y PAYER E...,2.500000e+08,USD,False,...,NA/Swap OIS USD,QZZGWPNBF5R3,BILT,N,True,9.9999999999,"1,200,000",NaN,None,None
42,NEWT-TRAD,1571154357000000201,2025-12-29 16:55:39+00:00,2025-12-29,2026-03-30,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 3M7Y RECEIVE...,2.300000e+08,USD,False,...,NA/Swap OIS USD,QZNLQ8T0N0SX,BILT,N,True,9.9999999999,"1,184,544",NaN,None,None
43,NEWT-TRAD,1571182935000000101,2025-12-29 16:57:47+00:00,2025-12-29,2030-01-08,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT 4Y1M1Y PAYER BER...,5.000000e+06,USD,False,...,NA/Swap Fxd Flt USD,QZ7XW3KWNFQ0,XXXX,N,False,,0,NaN,None,None
44,TERM-EXER,1571173140000000101,2025-12-29 16:58:57+00:00,2025-11-28,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y RECEIV...,2.700000e+07,USD,False,...,NA/Swap OIS USD,QZJ7PRWFV1G1,BILT,N,True,9.9999999999,"180,900.536",NaN,None,None
45,NEWT-TRAD,1571199675000000401,2025-12-29 16:59:19+00:00,2025-12-29,2030-09-17,SWAPTION_PAYER,USD-SOFR-COMPOUND 1D CONSTANT IMM_U2030IMM_Z20...,1.500000e+07,USD,False,...,NA/Swap Fxd Flt USD,QZ7XW3KWNFQ0,XXXX,N,False,,0,NaN,None,None
46,TERM-EXER,1571178714000000201,2025-12-29 16:59:39+00:00,2025-11-28,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y RECEIV...,1.400000e+07,USD,False,...,NA/Swap OIS USD,QZJ7PRWFV1G1,BILT,N,True,9.9999999999,"93,800.268",NaN,None,None
47,TERM-EXER,1571248326000000101,2025-12-29 17:02:43+00:00,2025-11-26,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y RECEIV...,1.300000e+07,USD,False,...,NA/Swap OIS USD,QZJ7PRWFV1G1,BILT,N,True,-1.39,"90,350.139",NaN,None,None
48,NEWT-TRAD,1571258610000000501,2025-12-29 17:04:11+00:00,2025-12-29,2026-01-29,SWAPTION_CHOOSER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y CHOOSE...,1.000000e+08,USD,False,...,NA/Swap OIS USD,QZMRJ6051HQB,BILT,N,False,,"1,220,000",NaN,None,None
49,TERM-EXER,1571259842000000101,2025-12-29 17:04:15+00:00,2025-11-26,2025-12-29,SWAPTION_RECEIVER,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y RECEIV...,2.700000e+07,USD,False,...,NA/Swap OIS USD,QZJ7PRWFV1G1,BILT,N,True,-1.39,"187,650.4448",NaN,None,None

In [18]:
sdf["package_type"].value_counts()

package_type
SWAPTION    143
STRADDLE    121
Name: count, dtype: int64

In [19]:
temp = sdf.copy()
temp["execution_timestamp"] = temp["execution_timestamp"].astype(str)
temp.to_excel("temp.xlsx", index=False)

In [43]:
temp = df[df["Dissemination Identifier"].isin(sdf["trade_id"])]
temp["Execution Timestamp"] = temp["Execution Timestamp"].astype(str)
temp["Event timestamp"] = temp["Event timestamp"].astype(str)
temp.to_excel("swaption_trades.xlsx",index=False)

C:\Users\chris\AppData\Local\Temp\ipykernel_79052\2697270985.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chris\AppData\Local\Temp\ipykernel_79052\2697270985.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
https://github.com/yieldcurvemonkey/SwapPulse/tree/3a2fdbf844e75d048f802b6f099ca8707e5879be

In [10]:
df[df["Dissemination Identifier"] == 1570700287000000601].iloc[-1].to_dict()

{'Dissemination Identifier': 1570700287000000601,
 'Original Dissemination Identifier': nan,
 'Action type': 'NEWT',
 'Event type': 'TRAD',
 'Event timestamp': Timestamp('2025-12-29 13:22:06+0000', tz='UTC'),
 'Amendment indicator': None,
 'Asset Class': 'IR',
 'Product name': None,
 'Cleared': 'N',
 'Mandatory clearing indicator': False,
 'Execution Timestamp': Timestamp('2025-12-29 13:11:18+0000', tz='UTC'),
 'Effective Date': Timestamp('2025-12-29 00:00:00'),
 'Expiration Date': Timestamp('2026-08-19 00:00:00'),
 'Maturity date of the underlier': datetime.date(2036, 8, 21),
 'Non-standardized term indicator': False,
 'Platform identifier': 'BILT',
 'Prime brokerage transaction indicator': False,
 'Block trade election indicator': False,
 'Large notional off-facility swap election indicator': False,
 'Notional amount-Leg 1': '45,000,000',
 'Notional amount-Leg 2': '45,000,000',
 'Notional currency-Leg 1': 'USD',
 'Notional currency-Leg 2': 'USD',
 'Notional quantity-Leg 1': None,
 'Notional quantity-Leg 2': None,
 'Total notional quantity-Leg 1': None,
 'Total notional quantity-Leg 2': None,
 'Quantity frequency multiplier-Leg 1': None,
 'Quantity frequency multiplier-Leg 2': None,
 'Quantity unit of measure-Leg 1': None,
 'Quantity unit of measure-Leg 2': None,
 'Quantity frequency-Leg 1': None,
 'Quantity frequency-Leg 2': None,
 'Notional amount in effect on associated effective date-Leg 1': '',
 'Notional amount in effect on associated effective date-Leg 2': '',
 'Effective date of the notional amount-Leg 1': '',
 'Effective date of the notional amount-Leg 2': '',
 'End date of the notional amount-Leg 1': '',
 'End date of the notional amount-Leg 2': '',
 'Call amount': None,
 'Call currency': None,
 'Put amount': None,
 'Put currency': None,
 'Exchange rate': None,
 'Exchange rate basis': None,
 'First exercise date': datetime.date(2026, 8, 19),
 'Fixed rate-Leg 1': 0.0385,
 'Fixed rate-Leg 2': nan,
 'Option Premium Amount': '0',
 'Option Premium Currency': 'XXX',
 'Price': None,
 'Price unit of measure': None,
 'Spread-Leg 1': 0.0,
 'Spread-Leg 2': 0.0,
 'Spread currency-Leg 1': '',
 'Spread currency-Leg 2': '',
 'Strike Price': 0.0385,
 'Strike price currency/currency pair': '',
 'Post-priced swap indicator': False,
 'Price currency': None,
 'Price notation': None,
 'Spread notation-Leg 1': 3.0,
 'Spread notation-Leg 2': 3.0,
 'Strike price notation': 3.0,
 'Fixed rate day count convention-leg 1': 'A004',
 'Fixed rate day count convention-leg 2': '',
 'Floating rate day count convention-leg 1': '',
 'Floating rate day count convention-leg 2': 'A004',
 'Floating rate reset frequency period-leg 1': '',
 'Floating rate reset frequency period-leg 2': 'YEAR',
 'Floating rate reset frequency period multiplier-leg 1': nan,
 'Floating rate reset frequency period multiplier-leg 2': 1.0,
 'Other payment amount': '',
 'Fixed rate payment frequency period-Leg 1': 'YEAR',
 'Floating rate payment frequency period-Leg 1': '',
 'Fixed rate payment frequency period-Leg 2': '',
 'Floating rate payment frequency period-Leg 2': 'YEAR',
 'Fixed rate payment frequency period multiplier-Leg 1': 1.0,
 'Floating rate payment frequency period multiplier-Leg 1': nan,
 'Fixed rate payment frequency period multiplier-Leg 2': nan,
 'Floating rate payment frequency period multiplier-Leg 2': 1.0,
 'Other payment type': '',
 'Other payment currency': '',
 'Settlement currency-Leg 1': 'USD',
 'Settlement currency-Leg 2': '',
 'Settlement location': '',
 'Collateralisation category': None,
 'Custom basket indicator': False,
 'Index factor': None,
 'Underlier ID-Leg 1': None,
 'Underlier ID-Leg 2': None,
 'Underlier ID source-Leg 1': None,
 'Underlying Asset Name': None,
 'Underlying asset subtype or underlying contract subtype-Leg 1': None,
 'Underlying asset subtype or underlying contract subtype-Leg 2': None,
 'Embedded Option type': '',
 'Option Type': None,
 'Option Style': None,
 'Package indicator': False,
 'Package transaction price': '',
 'Package transaction price currency': '',
 'Package transaction price notation': nan,
 'Package transaction spread': '',
 'Package transaction spread currency': '',
 'Package transaction spread notation': nan,
 'Physical delivery location-Leg 1': None,
 'Delivery Type': None,
 'Unique Product Identifier': 'QZMRJ6051HQB',
 'UPI FISN': 'NA/O Opt Epn OIS USD',
 'UPI Underlier Name': 'NA/Swap OIS USD'}