In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import sys
sys.path.append("../")

import nest_asyncio
nest_asyncio.apply()

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "vscode"            

import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.dates as mdates
plt.style.use('seaborn-v0_8-dark')
params = {'legend.fontsize': 'x-large',
        'figure.figsize': (16, 9),
        'axes.labelsize': 'x-large',
        'axes.titlesize':'x-large',
        'xtick.labelsize':'x-large',
        'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)

import pandas as pd
import numpy as np
import QuantLib as ql
import rateslib as rl

import datetime
import pytz
NY_tz = pytz.timezone("America/New_York") 
CHI_tz = pytz.timezone("America/Chicago") 
UTC_tz = pytz.timezone("UTC")

import warnings
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
)

In [2]:
cache_path = r"C:\Users\chris\clee\project-oasis\private\sdranalytics\.cache"
start = NY_tz.localize(datetime.datetime(2025, 12, 29, 0, 0))
end = NY_tz.localize(datetime.datetime(2025, 12, 29, 23, 59))

# from SDRUtils.data.builder import SDRDataBuilder
# sdr = SDRDataBuilder(cache_path=cache_path, show_tqdm=True)
# df = sdr.grab_sdr_trades(
# 	start_timestamp=start,
# 	end_timestamp=end,
# 	agency="CFTC",
# 	asset_class="RATES",
# )
# df

In [3]:
from SDRUtils.products.usd.usd_swaptions import USD_Swaptions

USD_Swaptions().build_classification_dataframe(start=start, end=end, cache_path=cache_path)

CACHE HIT...: 100%|██████████| 2/2 [00:00<00:00, 30.81it/s]
MERGING SLICES...: 100%|██████████| 2/2 [00:00<00:00, 177.30it/s]
Classifying Trades: 100%|██████████| 419/419 [00:00<00:00, 1712.43trade/s]

,Dissemination Identifier,trade_id,execution_timestamp,effective_date,expiration_date,product_type,tenor_years,tenor_label,is_forward,forward_start_years,forward_label,trade_label,notional,notional_currency,fixed_rate,strike,estimated_pv01,package_type,package_id,underlying_expiration_date
0,1570966806000001101,1570966806000001101,2025-11-20 21:09:53+00:00,2025-11-20,2025-12-29,USD-SOFR-OIS Compound 1D CONSTANT 1M10Y PAYER ...,0.108333,1M,None,0.000000,spot,spot 1M,0.0,USD,0.035675,0.035675,0.0,SWAPTION,None,2035-12-31
1,1572698398000000301,1572698398000000301,2025-11-24 16:26:22+00:00,2025-11-24,2026-10-26,USD-SOFR-OIS Compound 1D CONSTANT UNK RECEIVER...,0.933333,11M,None,0.000000,spot,spot 11M,63000000.0,USD,0.036275,0.036275,0.0,SWAPTION,None,NaT
2,1572714095000000101,1572714095000000101,2025-11-24 16:25:15+00:00,2025-11-24,2026-10-26,USD-SOFR-OIS Compound 1D CONSTANT UNK PAYER EU...,0.933333,11M,None,0.000000,spot,spot 11M,0.0,,0.036275,0.036275,0.0,SWAPTION,None,NaT
3,1570929476000000501,1570929476000000501,2025-11-24 16:51:25+00:00,2025-11-24,2025-12-29,USD-SOFR-OIS Compound 1D CONSTANT 1M31Y PAYER ...,0.097222,1M,None,0.000000,spot,spot 1M,23000000.0,USD,NaN,0.039530,0.0,SWAPTION,None,2055-12-31
4,1570929477000000601,1570929477000000601,2025-11-24 16:51:25+00:00,2025-11-24,2025-12-29,USD-SOFR-OIS Compound 1D CONSTANT 1M31Y RECEIV...,0.097222,1M,None,0.000000,spot,spot 1M,23000000.0,USD,NaN,0.039530,0.0,SWAPTION,None,2055-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,1574091013000000101,1574091013000000101,2025-12-29 21:32:43+00:00,2025-12-29,2034-10-11,USD-SOFR-OIS Compound 1D CONSTANT 9Y19Y PAYER ...,8.911111,9Y,None,0.000000,spot,spot 9Y,6000000.0,USD,0.038425,0.038425,0.0,SWAPTION,None,2044-10-13
408,1574096811000000201,1574096811000000201,2025-12-29 21:29:24+00:00,2025-12-29,2034-07-17,USD-SOFR-OIS Compound 1D CONSTANT 9Y19Y PAYER ...,8.672222,9Y,None,0.000000,spot,spot 9Y,13000000.0,USD,0.037790,0.037790,0.0,SWAPTION,None,2044-07-19
409,1574128757000000101,1574128757000000101,2025-12-29 21:33:15+00:00,2025-12-29,2034-10-11,USD-SOFR-OIS Compound 1D CONSTANT 9Y19Y RECEIV...,8.911111,9Y,None,0.000000,spot,spot 9Y,6000000.0,USD,0.038490,0.038490,0.0,SWAPTION,None,2044-10-13
410,1584541010000000101,1584541010000000101,2025-12-09 16:21:24+00:00,2025-12-08,2026-01-12,USD-SOFR-OIS Compound 1D CONSTANT 1M31Y PAYER ...,0.097222,1M,None,-0.002778,spot,spot 1M,40000000.0,USD,0.041100,0.041100,0.0,SWAPTION,None,2056-01-14
411,1584543272000000201,1584543272000000201,2025-12-09 16:21:24+00:00,2025-12-08,2026-01-12,USD-SOFR-OIS Compound 1D CONSTANT 1M31Y PAYER ...,0.097222,1M,None,-0.002778,spot,spot 1M,60000000.0,USD,0.041100,0.041100,0.0,SWAPTION,None,2056-01-14

In [ ]:
# from SDRUtils.products._swaptions.upi import make_swaption_desc_func, _build_upi_df

# swaption_upis = _build_upi_df()

# mask = df["Unique Product Identifier"].isin(swaption_upis["swaption_Identifier_UPI"])
# swaption_trades_df = df.loc[mask].copy()

# desc_fn = make_swaption_desc_func()

# swaption_trades_df.loc[:, "description"] = swaption_trades_df.apply(desc_fn, axis=1)
# swaption_trades_df

In [18]:
usd_swaption_trades = swaption_trades_df[(swaption_trades_df["Maturity date of the underlier"].notna())]
# usd_swaption_trades = swaption_trades_df
usd_swaption_trades[usd_swaption_trades["description"].str.contains("UNK")]

Empty DataFrame
Columns: [Dissemination Identifier, Original Dissemination Identifier, Action type, Event type, Event timestamp, Amendment indicator, Asset Class, Product name, Cleared, Mandatory clearing indicator, Execution Timestamp, Effective Date, Expiration Date, Maturity date of the underlier, Non-standardized term indicator, Platform identifier, Prime brokerage transaction indicator, Block trade election indicator, Large notional off-facility swap election indicator, Notional amount-Leg 1, Notional amount-Leg 2, Notional currency-Leg 1, Notional currency-Leg 2, Notional quantity-Leg 1, Notional quantity-Leg 2, Total notional quantity-Leg 1, Total notional quantity-Leg 2, Quantity frequency multiplier-Leg 1, Quantity frequency multiplier-Leg 2, Quantity unit of measure-Leg 1, Quantity unit of measure-Leg 2, Quantity frequency-Leg 1, Quantity frequency-Leg 2, Notional amount in effect on associated effective date-Leg 1, Notional amount in effect on associated effective date-Leg 2, Effective date of the notional amount-Leg 1, Effective date of the notional amount-Leg 2, End date of the notional amount-Leg 1, End date of the notional amount-Leg 2, Call amount, Call currency, Put amount, Put currency, Exchange rate, Exchange rate basis, First exercise date, Fixed rate-Leg 1, Fixed rate-Leg 2, Option Premium Amount, Option Premium Currency, Price, Price unit of measure, Spread-Leg 1, Spread-Leg 2, Spread currency-Leg 1, Spread currency-Leg 2, Strike Price, Strike price currency/currency pair, Post-priced swap indicator, Price currency, Price notation, Spread notation-Leg 1, Spread notation-Leg 2, Strike price notation, Fixed rate day count convention-leg 1, Fixed rate day count convention-leg 2, Floating rate day count convention-leg 1, Floating rate day count convention-leg 2, Floating rate reset frequency period-leg 1, Floating rate reset frequency period-leg 2, Floating rate reset frequency period multiplier-leg 1, Floating rate reset frequency period multiplier-leg 2, Other payment amount, Fixed rate payment frequency period-Leg 1, Floating rate payment frequency period-Leg 1, Fixed rate payment frequency period-Leg 2, Floating rate payment frequency period-Leg 2, Fixed rate payment frequency period multiplier-Leg 1, Floating rate payment frequency period multiplier-Leg 1, Fixed rate payment frequency period multiplier-Leg 2, Floating rate payment frequency period multiplier-Leg 2, Other payment type, Other payment currency, Settlement currency-Leg 1, Settlement currency-Leg 2, Settlement location, Collateralisation category, Custom basket indicator, Index factor, Underlier ID-Leg 1, Underlier ID-Leg 2, Underlier ID source-Leg 1, Underlying Asset Name, Underlying asset subtype or underlying contract subtype-Leg 1, Underlying asset subtype or underlying contract subtype-Leg 2, Embedded Option type, Option Type, Option Style, Package indicator, Package transaction price, ...]
Index: []

[0 rows x 111 columns]

In [10]:
temp = swaption_trades_df[swaption_trades_df["description"].str.contains("USD")]
temp["Execution Timestamp"] = temp["Execution Timestamp"].astype(str)
temp["Event timestamp"] = temp["Event timestamp"].astype(str)
temp.to_excel("swaption_trades.xlsx",index=False)

C:\Users\chris\AppData\Local\Temp\ipykernel_98788\771913721.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chris\AppData\Local\Temp\ipykernel_98788\771913721.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
swaption QZZGWPNBF5R3 USD CALL Euro Vanilla Phys, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys
swaption QZNLQ8T0N0SX USD PUTO Euro Vanilla Phys, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys

swaption QZMMWR8JKZQ8 USD PUTO Euro Vanilla Phys, underlying QZXG4P1G2KCS USD-SOFR-OIS Compound 1D Constant Phys 
swaption QZWXKVHB5F8V USD CALL Euro Vanilla Phys, underlying QZXG4P1G2KCS USD-SOFR-OIS Compound 1D Constant Phys 

swaption QZMRJ6051HQB USD OPTL Euro Vanilla Phys, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys 

swaption QZ7B7ZPS1LS5 USD PUTO Euro Vanilla Phys, underlying QZ8RQJKXHZP9 USD-SOFR-OIS Compound 1D Constant Cash

swaption QZXZSN00ZVCG USD PUTO Euro Vanilla Phys, underlying QZ1CXH05JJJH USD-SOFR-COMPOUND 1D Constant PHYS 
swaption QZXSN072GFF3 USD CALL Euro Vanilla Phys, underlying QZ1CXH05JJJH USD-SOFR-COMPOUND 1D Constant PHYS

swaption QZZLNQ2D4JQT USD CALL Euro Vanilla Phys, underlying QZKQ8QSWZKR2 USD-SOFR-OIS Compound 1Y Constant PHYS
swaption QZJ92TTHTSF0 USD PUTO Euro Vanilla Phys, underyying QZKQ8QSWZKR2 USD-SOFR-OIS Compound 1Y Constant PHYS
swaption QZHQPRHC3S7T USD OPTL Euro Vanilla Phys, underlying QZKQ8QSWZKR2 USD-SOFR-OIS Compound 1Y Constant PHYS
swaption QZJ7QTJM4H97 USD PUTO Euro Vanilla Cash, underlying QZKQ8QSWZKR2 USD-SOFR-OIS Compound 1Y Constant PHYS
swaption QZVLJBR2Z1VS USD Call Euro Vanilla Cash, underlying QZKQ8QSWZKR2 USD-SOFR-OIS Compound 1Y Constant PHYS

swaption QZKDXXXPW3X3 USD OPTL Euro Vanilla Phys, underlying QZ749DHWD023 USD-SOFR-COMPOUND 1D Constant Cash

swaption QZJ7PRWFV1G1 USD PUTO Euro Vanilla Cash, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys
swaption QZ1SC5570DC7 USD CALL Euro Vanilla Cash, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys
swaption QZJBL64PCV75 USD OPTL Euro Vanilla OPTL, underlying QZPB5VSBGRCD USD-SOFR-OIS Compound 1D Constant Phys

swaption QZ7XW3KWNFQ0 USD CALL BERM Vanilla Cash, underlying QZWVFGTL0HX0 USD-SOFR-COMPOUND 1D Constant Cash
swaption QZP4BJ4T4W9T USD CALL Euro Vanilla Cash, underlying QZWVFGTL0HX0 USD-SOFR-COMPOUND 1D Constant Cash

swaption QZC8L2PMNJZH USD PUTO Euro Vanilla Phys, underlying QZM88X1WWFMD USD-SOFR 1D Constant PHYS

swaption QZT2NCB2NRFJ USD Call Euro Vanilla Phys, underlying QZFDML7GL67S USD-LIBOR-BBA 3M Constant Cash

swaption QZRP1RVPFLQT USD PUTO Euro Vanilla Cash, underlying QZ5JTCF06XV6 USD-SOFR 1D Custom Cash
swaption QZX5JQN0TK24 USD Call Euro Vanilla Cash, underlying QZ5JTCF06XV6 USD-SOFR 1D Custom Cash

swaption QZBK1N7NJ0VF USD Call Euro Vanilla Phys, underlying QZ749DHWD023 USD-SOFR-COMPOUND 1D Constant Cash
swaption QZ2GZS235CHW USD PUTO Euro Vanilla Phys, underlying QZ749DHWD023 USD-SOFR-COMPOUND 1D Constant Cash

swaption QZTRSNZTX0F0 USD PUTO Berm Vanilla Phys, underlying QZPFD1BKD6MW USD-SOFR CME Term 1M Accreting Phys

swaption QZMC010F38PK USD PUTO Euro Vanilla Phys, underlying QZ1CMVCKP2QW USD-SOFR 3M Constant Phys
swaption QZVQ21ZLNJ5C USD OPTL Euro Vanilla Phys, underlying QZ1CMVCKP2QW USD-SOFR 3M Constant Phys
swaption QZJ03ZN7VKG7 USD Call Euro Vanilla Cash, underlying QZ1CMVCKP2QW USD-SOFR 3M Constant Phys

In [128]:
# import datetime
# from gs_quant.data import Dataset
# from gs_quant.session import GsSession

# gs_client_id = "2eb2f48872304c1d94fa1642fa691afe"
# gs_secret_key = "91cb9c89110495d1f62d0ab0c4014555c992c2509de8f5ae2b8bf1a2d3c86bd4"
# GsSession.use(client_id=gs_client_id, client_secret=gs_secret_key, scopes=('read_product_data',))

# usd_sofr_1y10y_asset_id = "MA3YAP9YTBN0HAM4"

# start = datetime.date(2025, 1, 1)
# end = datetime.date(2025, 11, 20)

# df = Dataset("IR_SWAPTION_VOLS_V1_STANDARD").get_data(start=start, end=end, assetId=usd_sofr_1y10y_asset_id)

# df["bpvol_yr"] = df["impliedNormalVolatility"] * (252 ** (0.5))

# df