In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import nest_asyncio
nest_asyncio.apply()

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "vscode"            

import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.dates as mdates
plt.style.use('ggplot')
params = {'legend.fontsize': 'medium',
        'figure.figsize': (20, 12),
        'axes.labelsize': 'medium',
        'axes.titlesize':'medium',
        'xtick.labelsize':'medium',
        'ytick.labelsize':'medium'}
pylab.rcParams.update(params)

import pandas as pd
import numpy as np
import rateslib as rl
import QuantLib as ql

import time
import datetime
import pytz

NYC_tz = pytz.timezone("America/New_York") 
CHI_tz = pytz.timezone("America/Chicago") 
LDN_tz = pytz.timezone("Europe/London") 
UTC_tz = pytz.timezone("UTC") 

import sys
sys.path.append("../../")

from RVUtils.plt_timeseries import make_secondary_axis_plot

In [2]:
from MDP.IRSwaps.IRSwapsMDP import IRSwapsMDP
from Query.Unified.registry import UnifiedValue
from Query.Unified.UnifiedQuery import UnifiedQuery
from TB.IRSwapsTB import IRSwapsTB
from TB.TimeseriesBuilder import TimeseriesBuilder

In [3]:
curve_mdp = IRSwapsMDP(source="BARCHART_STIRF-RL")
ts_builder = TimeseriesBuilder()

In [8]:
start = NYC_tz.localize(datetime.datetime(2026, 7, 13, 7, 00))
end = NYC_tz.localize(datetime.datetime(2026, 7, 22, 17, 00))

q = UnifiedQuery(
    curve="USD-SOFR-1D-Q12STIRT",
    tenor="IMM_U26xIMM_Z26/IMM_U27xIMM_Z27",
    value=UnifiedValue.IRS_RATE,
)
# q = UnifiedQuery(
#     curve="USD-OIS-Q12xM12STIRT-SERFFX-MIX23",
#     tenor="fomc_sep26/IMM_U2027xIMM_Z2027",
#     value=UnifiedValue.IRS_RATE,
# )
# q1 = UnifiedQuery(
#     curve="USD-SOFR-1D-Q12STIRT",
#     tenor="IMM_H27xIMM_M27",
#     value=UnifiedValue.IRS_RATE,
# )
# q2 = UnifiedQuery(
#     curve="USD-SOFR-1D-Q12STIRT",
#     tenor="IMM_U27xIMM_Z27",
#     value=UnifiedValue.IRS_RATE,
# )
# q3 = UnifiedQuery(
#     curve="USD-SOFR-1D-Q12STIRT",
#     tenor="IMM_U26xIMM_Z26/IMM_H27xIMM_M27/IMM_U27xIMM_Z27",
#     value=UnifiedValue.IRS_RATE,
# )
df = ts_builder.get_timeseries(
    start=start,
    end=end,
    # queries=[q, q1, q2, q3],
    queries=[q,],
    freq="1min",
    n_jobs=12,
    routers={
        "IRS": IRSwapsTB(curve_mdp, show_tqdm=True),
    },
    # ignore_cache_miss=True,
)
df

                           USD-SOFR-1D IMM_U26xIMM_Z26/IMM_U27xIMM_Z27 CURVE RATE
Date
2026-07-13 07:00:00-04:00                                          16.999997
2026-07-13 07:01:00-04:00                                          16.999997
2026-07-13 07:02:00-04:00                                          16.999997
2026-07-13 07:03:00-04:00                                          16.999998
2026-07-13 07:04:00-04:00                                          16.999998
...                                                                      ...
2026-07-22 16:56:00-04:00                                          20.999998
2026-07-22 16:57:00-04:00                                          20.999998
2026-07-22 16:58:00-04:00                                          20.999998
2026-07-22 16:59:00-04:00                                          20.499998
2026-07-22 17:00:00-04:00                                          20.499998

[10268 rows x 1 columns]

In [9]:
plot, fig, ax, ax2, legend = make_secondary_axis_plot(engine="plotly")
plot(
    # df[q.col_name().replace("-Q12STIRT", "")],
    # df["USD-OIS fomc_jul26/fomc_dec26 CURVE RATE"],
    df["USD-SOFR-1D IMM_U26xIMM_Z26/IMM_U27xIMM_Z27 CURVE RATE"],
    which="left",
    indicators=[
        # {"kind": "last", "style": {"linestyle": "--", "linewidth": 1.2, "color": "tab:purple"}},  
        # {"kind": "sma", "window": 60, "style": {"linestyle": "--", "color": "green"}},
    ],
    # ou={"enable": True, "steps": 126, "add_metrics_to_legend": True}
)
legend(show_date=True, loc="upper left")
plt.show()

In [11]:
curve_mdp = IRSwapsMDP(source="BARCHART_STIRF-RL")
ts_builder = TimeseriesBuilder()

start = NYC_tz.localize(datetime.datetime(2024, 1, 1, 18, 00))
end = NYC_tz.localize(datetime.datetime(2026, 6, 22, 17, 00))
# end = "live"

eod_df = ts_builder.get_timeseries(
    start=start,
    end=end,
    queries=[
        # UnifiedQuery(
        #     curve="CAD-CORRA-Q8STIRT",
        #     tenor="IMM_Z26xIMM_H27",
        #     value=UnifiedValue.IRS_RATE,
        # ),
        # UnifiedQuery(
        #     curve="USD-SOFR-1D-Q12STIRT",
        #     tenor="1y/1y1y/2y1y",
        #     value=UnifiedValue.IRS_RATE,
        # ),
		# UnifiedQuery(
        #     curve="USD-SOFR-1D-Q12STIRT",
        #     tenor="1y/1y1y/2y1y",
        #     value=UnifiedValue.IRS_RATE,
        # ),
		UnifiedQuery(
            curve="USD-SOFR-1D-Q12STIRT",
            tenor="2y1y",
            value=UnifiedValue.IRS_RATE,
        ),
        # UnifiedQuery(
        #     curve="USD-SOFR-1D-Q12STIRT",
        #     tenor="IMM_6xIMM_7/IMM_10xIMM_11",
        #     value=UnifiedValue.IRS_RATE,
        # ),
        # UnifiedQuery(
        #     curve="CAD-CORRA-Q8STIRT",
        #     tenor="IMM_Z28xIMM_H29",
        #     value=UnifiedValue.IRS_RATE,
        # ),
        # UnifiedQuery(
        #     curve="USD-SOFR-1D-Q12STIRT",
        #     tenor="IMM_Z28xIMM_H29",
        #     value=UnifiedValue.IRS_RATE,
        # ),
    ],
    freq="nyc_eod",
    n_jobs=16,
    routers={
        "IRS": IRSwapsTB(curve_mdp, show_tqdm=True),
    },
    ignore_cache_miss=True,
)

# eod_df["USD Z6Z8"] = (eod_df["USD-SOFR-1D IMM_Z28xIMM_H29 OUTRIGHT RATE"] - eod_df["USD-SOFR-1D IMM_Z26xIMM_H27 OUTRIGHT RATE"]) * 100
# eod_df["CAD Z6Z8"] = (eod_df["CAD-CORRA IMM_Z28xIMM_H29 OUTRIGHT RATE"] - eod_df["CAD-CORRA IMM_Z26xIMM_H27 OUTRIGHT RATE"]) * 100
# eod_df["USDCAD Z6Z8"] = (eod_df["USD Z6Z8"] - eod_df["CAD Z6Z8"]) * 100
# eod_df["USDCAD Z6"] = (eod_df["USD-SOFR-1D IMM_Z26xIMM_H27 OUTRIGHT RATE"] - eod_df["CAD-CORRA IMM_Z26xIMM_H27 OUTRIGHT RATE"]) * 100 
# eod_df["USDCAD Z8"] = (eod_df["USD-SOFR-1D IMM_Z28xIMM_H29 OUTRIGHT RATE"] - eod_df["CAD-CORRA IMM_Z28xIMM_H29 OUTRIGHT RATE"]) * 100 

eod_df

                           USD-SOFR-1D 2y1y OUTRIGHT RATE
Date
2024-01-02 17:00:00-05:00                        3.233244
2024-01-03 17:00:00-05:00                        3.221666
2024-01-04 17:00:00-05:00                        3.328558
2024-01-05 17:00:00-05:00                        3.366300
2024-01-08 17:00:00-05:00                        3.371177
...                                                   ...
2026-06-12 17:00:00-04:00                        3.927142
2026-06-15 17:00:00-04:00                        3.897571
2026-06-16 17:00:00-04:00                        3.860638
2026-06-17 17:00:00-04:00                        3.939088
2026-06-18 17:00:00-04:00                        3.907355

[625 rows x 1 columns]

In [21]:
plot, fig, ax, ax2, legend = make_secondary_axis_plot(engine="plotly")
plot(
    eod_df["USD-SOFR-1D 2y1y OUTRIGHT RATE"],
    which="left",
    indicators=[
        # {"kind": "last", },  
        # {"kind": "last", "style": {"linestyle": "--", "linewidth": 1.2, "color": "tab:purple"}},  
        # {"kind": "sma", "window": 60, "style": {"linestyle": "--", "color": "green"}},
    ],
    # ou={"enable": True, "steps": 126, "add_metrics_to_legend": True}
)
# plot(eod_df["USD-SOFR-1D 1y1y OUTRIGHT RATE"], which="right")

legend(show_date=True, loc="upper left")
plt.show()