In [3]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import sys
sys.path.append("../../")

import nest_asyncio
nest_asyncio.apply()

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "vscode"            

import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.dates as mdates
plt.style.use('seaborn-v0_8-dark')
params = {'legend.fontsize': 'x-large',
        'figure.figsize': (16, 9),
        'axes.labelsize': 'x-large',
        'axes.titlesize':'x-large',
        'xtick.labelsize':'x-large',
        'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)

import pandas as pd
import numpy as np
import QuantLib as ql
import rateslib as rl

import datetime
import pytz
NY_tz = pytz.timezone("America/New_York") 
CHI_tz = pytz.timezone("America/Chicago") 
UTC_tz = pytz.timezone("UTC")

import warnings
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
df = pd.read_csv(r"C:\Users\chris\Downloads\CFTC_CUMULATIVE_FOREX_2026_07_09\CFTC_CUMULATIVE_FOREX_2026_07_09.csv")
df["Unique Product Identifier"].value_counts()
df["Exchange rate basis"].value_counts().head(50)

C:\Users\chris\AppData\Local\Temp\ipykernel_84568\3618460179.py:1: DtypeWarning:

Columns (35,102) have mixed types. Specify dtype option on import or set low_memory=False.

Exchange rate basis
USD/KRW    17426
USD/INR     9139
USD/TWD     8423
USD/BRL     4277
USD/IDR     3264
USD/PHP     2416
USD/CLP     2273
USD/COP     1726
KRW/USD      890
INR/USD      759
EUR/USD      722
USD/JPY      664
USD/CNY      604
TWD/USD      447
USD/PEN      368
AUD/USD      360
USD/MXN      332
GBP/USD      302
BRL/USD      292
IDR/USD      288
USD/CAD      277
COP/USD      243
PHP/USD      225
USD/EUR      224
USD/MYR      212
CLP/USD      203
CAD/USD      201
EUR/GBP      168
USD/ZAR      123
EUR/KRW      120
EUR/HUF      119
NZD/USD      119
USD/HKD      111
USD/CHF      106
USD/AUD      101
JPY/USD       97
CAD/BRL       92
EUR/AUD       92
AUD/NZD       91
EUR/BRL       90
CNY/USD       87
USD/VND       86
JPY/EUR       76
EUR/PLN       75
GBP/EUR       73
USD/KZT       68
EUR/CHF       67
EUR/CNY       66
USD/NZD       64
USD/EGP       64
Name: count, dtype: int64

In [12]:
cache_path = r"C:\Users\chris\clee\project-oasis\private\sdranalytics\.cache"

# as_of = datetime.date(2026, 2, 23)
# start = NY_tz.localize(datetime.datetime(as_of.year, as_of.month, as_of.day, 0, 0))
# end = NY_tz.localize(datetime.datetime(as_of.year, as_of.month, as_of.day, 23, 59))

start = NY_tz.localize(datetime.datetime(2026, 7, 10, 0, 0))
end = NY_tz.localize(datetime.datetime(2026, 7, 10, 23, 59))

# mdp = IRSwapsMDP(source="ERIS_EOD_LIVE-QL_BASIC")
# pricer = mdp.get_pricer(request=dict(curve_name="USD-SOFR-1D", timestamp=start.date()))

from SDRUtils.data.builder import SDRDataBuilder
sdr = SDRDataBuilder(cache_path=cache_path, show_tqdm=True)
df = sdr.grab_sdr_trades(
	start_timestamp=start,
	end_timestamp=end,
	agency="CFTC",
	asset_class="RATES",
)
df

CACHE HIT...: 100%|██████████| 1/1 [00:00<00:00, 13.13it/s]

,Dissemination Identifier,Original Dissemination Identifier,Action type,Event type,Event timestamp,Amendment indicator,Asset Class,Product name,Cleared,Mandatory clearing indicator,...,Package transaction price notation,Package transaction spread,Package transaction spread currency,Package transaction spread notation,Physical delivery location-Leg 1,Delivery Type,Unique Product Identifier,UPI FISN,UPI Underlier Name,file_date
0,4117894927000000601,,NEWT,TRAD,2026-07-10 04:00:08+00:00,None,IR,None,I,False,...,NaN,,,NaN,None,None,QZB883814F13,NA/Swap OIS INR,INR-MIBOR-OIS Compound,2026-07-10
1,4117894055000000101,,NEWT,TRAD,2026-07-10 04:00:25+00:00,None,IR,None,I,False,...,NaN,,,NaN,None,None,QZNSX4NZX325,NA/Swap Fxd Flt KRW,KRW-CD-KSDA-Bloomberg,2026-07-10
2,4117894056000000201,,NEWT,TRAD,2026-07-10 04:00:29+00:00,None,IR,None,I,False,...,NaN,,,NaN,None,None,QZB883814F13,NA/Swap OIS INR,INR-MIBOR-OIS Compound,2026-07-10
3,4117894057000000301,,NEWT,TRAD,2026-07-10 04:00:35+00:00,None,IR,None,I,False,...,NaN,,,NaN,None,None,QZB883814F13,NA/Swap OIS INR,INR-MIBOR-OIS Compound,2026-07-10
4,4117897702000000301,,NEWT,TRAD,2026-07-10 04:00:55+00:00,None,IR,None,N,False,...,NaN,,,NaN,None,None,QZR118Q9NWN9,NA/Swap Flt Flt JPY USD,JPY-TONA-OIS Compound vs USD-SOFR-OIS Compound,2026-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12374,4140171870000000401,4140171868000000201,CORR,,2026-07-10 22:03:37+00:00,None,IR,None,N,False,...,1.0,,,NaN,None,None,QZ43KHZW90D5,NA/O P Epn OIS USD,NA/Swap OIS USD,2026-07-10
12375,4140190149000000201,,NEWT,TRAD,2026-07-10 22:10:28+00:00,None,IR,None,N,False,...,1.0,,,NaN,None,None,QZ63QRQHX2ZT,NA/O Call Epn OIS USD,NA/Swap OIS USD,2026-07-10
12376,4140192131000000101,4140190148000000101,CORR,,2026-07-10 22:10:33+00:00,None,IR,None,N,False,...,1.0,,,NaN,None,None,QZ43KHZW90D5,NA/O P Epn OIS USD,NA/Swap OIS USD,2026-07-10
12377,4140618520000000201,4139526797000000101,CORR,,2026-07-10 22:40:40+00:00,None,IR,None,I,False,...,NaN,,,NaN,None,None,QZD55DZNSRR9,NA/Swap OIS BRL,BRL-CDI,2026-07-10
12378,4141150661000000101,,NEWT,TRAD,2026-07-10 23:31:05+00:00,None,IR,None,N,False,...,NaN,,,NaN,None,None,QZ60F6DDX99F,NA/O Nstd Oth USD,USD-SOFR ICE Swap Rate,2026-07-10

In [7]:
[col for col in list(df.columns) if "pay" in str(col).lower()]

['Other payment amount',
 'Fixed rate payment frequency period-Leg 1',
 'Floating rate payment frequency period-Leg 1',
 'Fixed rate payment frequency period-Leg 2',
 'Floating rate payment frequency period-Leg 2',
 'Fixed rate payment frequency period multiplier-Leg 1',
 'Floating rate payment frequency period multiplier-Leg 1',
 'Fixed rate payment frequency period multiplier-Leg 2',
 'Floating rate payment frequency period multiplier-Leg 2',
 'Other payment type',
 'Other payment currency']

In [1]:
import requests
res = requests.get("https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/")
res.text

'<!DOCTYPE html>\n<html class="no-touch" lang="en-GB" xmlns="http://www.w3.org/1999/xhtml">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="profile" href="http://gmpg.org/xfn/11">\n<link rel="pingback" href="https://www.astorridge.com/xmlrpc.php">\n<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n\n\t<!-- This site is optimized with the Yoast SEO plugin v20.9 - https://yoast.com/wordpress/plugins/seo/ -->\n\t<title>Trade Radar - RV trades in Europe 26th Nov, James Rice @Astor Ridge - Astorridge</title>\n\t<link rel="canonical" href="https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/" />\n\t<meta property="og:locale" content="en_GB" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="Trade Radar - RV trades in Europe 26th Nov, James Rice @Astor Ridge - Astorridge" />\n\t<meta property="og:description" content="This content is restricted to registered users. If you are an existing user, please log in. New users may register [&hellip;]" />\n\t<meta property="og:url" content="https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/" />\n\t<meta property="og:site_name" content="Astorridge" />\n\t<meta property="article:published_time" content="2019-11-26T10:16:10+00:00" />\n\t<meta property="article:modified_time" content="2019-11-26T10:19:13+00:00" />\n\t<meta property="og:image" content="https://www.astorridge.com/wp-content/uploads/2019/11/image001-1.png" />\n\t<meta name="author" content="James_Rice" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:label1" content="Written by" />\n\t<meta name="twitter:data1" content="James_Rice" />\n\t<meta name="twitter:label2" content="Estimated reading time" />\n\t<meta name="twitter:data2" content="5 minutes" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/","url":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/","name":"Trade Radar - RV trades in Europe 26th Nov, James Rice @Astor Ridge - Astorridge","isPartOf":{"@id":"https://www.astorridge.com/#website"},"primaryImageOfPage":{"@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/#primaryimage"},"image":{"@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/#primaryimage"},"thumbnailUrl":"https://www.astorridge.com/wp-content/uploads/2019/11/image001-1.png","datePublished":"2019-11-26T10:16:10+00:00","dateModified":"2019-11-26T10:19:13+00:00","author":{"@id":"https://www.astorridge.com/#/schema/person/ac8abc5f589a516683b2fca7de848102"},"breadcrumb":{"@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/#breadcrumb"},"inLanguage":"en-GB","potentialAction":[{"@type":"ReadAction","target":["https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/"]}]},{"@type":"ImageObject","inLanguage":"en-GB","@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/#primaryimage","url":"https://www.astorridge.com/wp-content/uploads/2019/11/image001-1.png","contentUrl":"https://www.astorridge.com/wp-content/uploads/2019/11/image001-1.png","width":516,"height":216},{"@type":"BreadcrumbList","@id":"https://www.astorridge.com/trade-radar-rv-trades-in-europe-26th-nov-james-rice-astor-ridge/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.astorridge.com/"},{"@type":"ListItem","position":2,"name":"Trade Radar &#8211; RV trades in Europe 26th Nov, James Rice @Astor Ridge"}]},{"@type":"WebSite","@id":"https://www.astorridge.com/#website","url":"https://www.astorridge.com/","name":"Astorridge","description":"","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.astorridge.com/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-GB"},{"@type":"Person","@id":"https://www.astorridge.com/#/schema/person/ac8abc5f589a516683b2fca7de848102","name":"James_Rice","url":"https://www.astorridge.com/author/james_rice/"}]}</script>\n\t<!-- / Yoast SEO plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//fonts.googleapis.com\' />\n<link rel="alternate" type="application/rss+xml" title="Astorridge &raquo; Feed" href="https://www.astorridge.com/feed/" />\n<link rel="alternate" type="application/rss+xml" title="Astorridge &raquo; Comments Feed" href="https://www.astorridge.com/comments/feed/" />\n<script type="text/javascript">\nwindow._wpemojiSettings = {"baseUrl":"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/14.0.0\\/72x72\\/","ext":".png","svgUrl":"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/14.0.0\\/svg\\/","svgExt":".svg","source":{"concatemoji":"https:\\/\\/www.astorridge.com\\/wp-includes\\/js\\/wp-emoji-release.min.js?ver=6.2.9"}};\n/*! This file is auto-generated */\n!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){p.clearRect(0,0,i.width,i.height),p.fillText(e,0,0);e=i.toDataURL();return p.clearRect(0,0,i.width,i.height),p.fillText(t,0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(p&&p.fillText)switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s("\\ud83c\\udff3\\ufe0f\\u200d\\u26a7\\ufe0f","\\ud83c\\udff3\\ufe0f\\u200b\\u26a7\\ufe0f")?!1:!s("\\ud83c\\uddfa\\ud83c\\uddf3","\\ud83c\\uddfa\\u200b\\ud83c\\uddf3")&&!s("\\ud83c\\udff4\\udb40\\udc67\\udb40\\udc62\\udb40\\udc65\\udb40\\udc6e\\udb40\\udc67\\udb40\\udc7f","\\ud83c\\udff4\\u200b\\udb40\\udc67\\u200b\\udb40\\udc62\\u200b\\udb40\\udc65\\u200b\\udb40\\udc6e\\u200b\\udb40\\udc67\\u200b\\udb40\\udc7f");case"emoji":return!s("\\ud83e\\udef1\\ud83c\\udffb\\u200d\\ud83e\\udef2\\ud83c\\udfff","\\ud83e\\udef1\\ud83c\\udffb\\u200b\\ud83e\\udef2\\ud83c\\udfff")}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],"flag"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(e=t.source||{}).concatemoji?c(e.concatemoji):e.wpemoji&&e.twemoji&&(c(e.twemoji),c(e.wpemoji)))}(window,document,window._wpemojiSettings);\n</script>\n<style type="text/css">\nimg.wp-smiley,\nimg.emoji {\n\tdisplay: inline !important;\n\tborder: none !important;\n\tbox-shadow: none !important;\n\theight: 1em !important;\n\twidth: 1em !important;\n\tmargin: 0 0.07em !important;\n\tvertical-align: -0.1em !important;\n\tbackground: none !important;\n\tpadding: 0 !important;\n}\n</style>\n\t<link rel="stylesheet" href="https://www.astorridge.com/wp-content/cache/minify/4b40a.css" media="all" />\r\n\n<link rel=\'stylesheet\' id=\'ls-google-fonts-css\' href=\'https://fonts.googleapis.com/css?family=Lato:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i%7COpen+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i%7CIndie+Flower:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i%7COswald:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\' type=\'text/css\' media=\'all\' />\n<link rel="stylesheet" href="https://www.astorridge.com/wp-content/cache/minify/d7cb9.css" media="all" />\r\n\n\n<style id=\'global-styles-inline-css\' type=\'text/css\'>\nbody{--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--duotone--dark-grayscale: url(\'#wp-duotone-dark-grayscale\');--wp--preset--duotone--grayscale: url(\'#wp-duotone-grayscale\');--wp--preset--duotone--purple-yellow: url(\'#wp-duotone-purple-yellow\');--wp--preset--duotone--blue-red: url(\'#wp-duotone-blue-red\');--wp--preset--duotone--midnight: url(\'#wp-duotone-midnight\');--wp--preset--duotone--magenta-yellow: url(\'#wp-duotone-magenta-yellow\');--wp--preset--duotone--purple-green: url(\'#wp-duotone-purple-green\');--wp--preset--duotone--blue-orange: url(\'#wp-duotone-blue-orange\');--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);}:where(.is-layout-flex){gap: 0.5em;}body .is-layout-flow > .alignleft{float: left;margin-inline-start: 0;margin-inline-end: 2em;}body .is-layout-flow > .alignright{float: right;margin-inline-start: 2em;margin-inline-end: 0;}body .is-layout-flow > .aligncenter{margin-left: auto !important;margin-right: auto !important;}body .is-layout-constrained > .alignleft{float: left;margin-inline-start: 0;margin-inline-end: 2em;}body .is-layout-constrained > .alignright{float: right;margin-inline-start: 2em;margin-inline-end: 0;}body .is-layout-constrained > .aligncenter{margin-left: auto !important;margin-right: auto !important;}body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)){max-width: var(--wp--style--global--content-size);margin-left: auto !important;margin-right: auto !important;}body .is-layout-constrained > .alignwide{max-width: var(--wp--style--global--wide-size);}body .is-layout-flex{display: flex;}body .is-layout-flex{flex-wrap: wrap;align-items: center;}body .is-layout-flex > *{margin: 0;}:where(.wp-block-columns.is-layout-flex){gap: 2em;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}\n.wp-block-navigation a:where(:not(.wp-element-button)){color: inherit;}\n:where(.wp-block-columns.is-layout-flex){gap: 2em;}\n.wp-block-pullquote{font-size: 1.5em;line-height: 1.6;}\n</style>\n<link rel=\'stylesheet\' id=\'uncodefont-google-css\' href=\'//fonts.googleapis.com/css?family=Poppins%3A300%2Cregular%2C500%2C600%2C700%7CHind%3A300%2Cregular%2C500%2C600%2C700%7CDroid+Serif%3Aregular%2Citalic%2C700%2C700italic%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CPlayfair+Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic%7COswald%3A300%2Cregular%2C700%7CRoboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic%7CSource+Sans+Pro%3A200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C600%2C600italic%2C700%2C700italic%2C900%2C900italic%7CAntic+Slab%3Aregular&#038;subset=devanagari%2Clatin-ext%2Clatin%2Ccyrillic%2Cvietnamese%2Cgreek%2Ccyrillic-ext%2Cgreek-ext&#038;ver=2.2.8\' type=\'text/css\' media=\'all\' />\n<link rel="stylesheet" href="https://www.astorridge.com/wp-content/cache/minify/71b03.css" media="all" />\r\n\n<style id=\'uncode-style-inline-css\' type=\'text/css\'>\n\n@media (max-width: 959px) { .navbar-brand > * { height: 50px !important;}}\n@media (min-width: 960px) { .limit-width { max-width: 1200px; margin: auto;}}\n.menu-primary ul.menu-smart > li > a, .menu-primary ul.menu-smart li.dropdown > a, .menu-primary ul.menu-smart li.mega-menu > a, .vmenu-container ul.menu-smart > li > a, .vmenu-container ul.menu-smart li.dropdown > a { text-transform: uppercase; }\n.menu-primary ul.menu-smart ul a, .vmenu-container ul.menu-smart ul a { text-transform: uppercase; }\n#changer-back-color { transition: background-color 1000ms cubic-bezier(0.25, 1, 0.5, 1) !important; } #changer-back-color > div { transition: opacity 1000ms cubic-bezier(0.25, 1, 0.5, 1) !important; } body.bg-changer-init.disable-h

In [21]:
# df["Event timestamp"] = df["Event timestamp"].astype(str)
# df["Execution Timestamp"] = df["Execution Timestamp"].astype(str)
# df.to_csv(r"C:\Users\chris\clee\ARBS\notebooks\sdr\april_fomc_dated_sdr_trades.csv", index=False)

In [3]:
# df[(df["Effective Date"].dt.date == datetime.date(2026, 4, 28)) & (df["Expiration Date"].dt.date == datetime.date(2026, 6, 16))]

In [28]:
# df[(df["UPI Underlier Name"].str.contains("vs", case=False, na=False))]["UPI Underlier Name"].value_counts()

# df[df["UPI Underlier Name"] == "USD-Federal Funds-OIS Compound vs USD-SOFR-OIS Compound"]

df[df["Dissemination Identifier"] == "4135370792000000201"][
    [
        "Dissemination Identifier",
        "Original Dissemination Identifier",
        "Effective Date",
        "Expiration Date",
        "Cleared",
        "Event timestamp",
        "Execution Timestamp",
        'Notional amount-Leg 1',
        "Package transaction price",
		'Package transaction spread',
		'Exchange rate basis',
		'Spread-Leg 1',
		'Spread-Leg 2',
        'Fixed rate-Leg 1',
        'Fixed rate-Leg 2',
		'Price',
        'Other payment amount',
        'UPI Underlier Name'
    ]
].to_dict(orient="records")

[{'Dissemination Identifier': '4135370792000000201',
  'Original Dissemination Identifier': '',
  'Effective Date': Timestamp('2026-07-29 00:00:00'),
  'Expiration Date': Timestamp('2026-09-16 00:00:00'),
  'Cleared': 'I',
  'Event timestamp': Timestamp('2026-07-10 16:57:28+0000', tz='UTC'),
  'Execution Timestamp': Timestamp('2026-07-10 16:57:28+0000', tz='UTC'),
  'Notional amount-Leg 1': '7,400,000,000',
  'Package transaction price': '-48,419',
  'Package transaction spread': '',
  'Exchange rate basis': None,
  'Spread-Leg 1': nan,
  'Spread-Leg 2': nan,
  'Fixed rate-Leg 1': '0.037097',
  'Fixed rate-Leg 2': nan,
  'Price': None,
  'Other payment amount': '22998.45996',
  'UPI Underlier Name': 'USD-Federal Funds-OIS Compound'}]

In [26]:
df[df["Dissemination Identifier"] == "4136247796000000201"].to_dict(orient="records")

[{'Dissemination Identifier': '4136247796000000201',
  'Original Dissemination Identifier': '',
  'Action type': 'NEWT',
  'Event type': 'TRAD',
  'Event timestamp': Timestamp('2026-07-10 17:38:47+0000', tz='UTC'),
  'Amendment indicator': None,
  'Asset Class': 'IR',
  'Product name': None,
  'Cleared': 'I',
  'Mandatory clearing indicator': False,
  'Execution Timestamp': Timestamp('2026-07-10 17:38:47+0000', tz='UTC'),
  'Effective Date': Timestamp('2026-07-14 00:00:00'),
  'Expiration Date': Timestamp('2038-07-14 00:00:00'),
  'Maturity date of the underlier': None,
  'Non-standardized term indicator': False,
  'Platform identifier': 'TSEF',
  'Prime brokerage transaction indicator': False,
  'Block trade election indicator': False,
  'Large notional off-facility swap election indicator': None,
  'Notional amount-Leg 1': '250,000,000+',
  'Notional amount-Leg 2': '250,000,000+',
  'Notional currency-Leg 1': 'USD',
  'Notional currency-Leg 2': 'USD',
  'Notional quantity-Leg 1': None,
  'Notional quantity-Leg 2': None,
  'Total notional quantity-Leg 1': None,
  'Total notional quantity-Leg 2': None,
  'Quantity frequency multiplier-Leg 1': None,
  'Quantity frequency multiplier-Leg 2': None,
  'Quantity unit of measure-Leg 1': None,
  'Quantity unit of measure-Leg 2': None,
  'Quantity frequency-Leg 1': None,
  'Quantity frequency-Leg 2': None,
  'Notional amount in effect on associated effective date-Leg 1': '',
  'Notional amount in effect on associated effective date-Leg 2': '',
  'Effective date of the notional amount-Leg 1': '',
  'Effective date of the notional amount-Leg 2': '',
  'End date of the notional amount-Leg 1': '',
  'End date of the notional amount-Leg 2': '',
  'Call amount': None,
  'Call currency': None,
  'Put amount': None,
  'Put currency': None,
  'Exchange rate': None,
  'Exchange rate basis': None,
  'First exercise date': None,
  'Fixed rate-Leg 1': '',
  'Fixed rate-Leg 2': 0.04219375,
  'Option Premium Amount': '',
  'Option Premium Currency': '',
  'Price': None,
  'Price unit of measure': None,
  'Spread-Leg 1': 0.0,
  'Spread-Leg 2': nan,
  'Spread currency-Leg 1': '',
  'Spread currency-Leg 2': '',
  'Strike Price': nan,
  'Strike price currency/currency pair': '',
  'Post-priced swap indicator': False,
  'Price currency': None,
  'Price notation': None,
  'Spread notation-Leg 1': 3.0,
  'Spread notation-Leg 2': nan,
  'Strike price notation': nan,
  'Fixed rate day count convention-leg 1': '',
  'Fixed rate day count convention-leg 2': 'A004',
  'Floating rate day count convention-leg 1': 'A004',
  'Floating rate day count convention-leg 2': '',
  'Floating rate reset frequency period-leg 1': 'YEAR',
  'Floating rate reset frequency period-leg 2': '',
  'Floating rate reset frequency period multiplier-leg 1': 1.0,
  'Floating rate reset frequency period multiplier-leg 2': nan,
  'Other payment amount': '',
  'Fixed rate payment frequency period-Leg 1': '',
  'Floating rate payment frequency period-Leg 1': 'YEAR',
  'Fixed rate payment frequency period-Leg 2': 'YEAR',
  'Floating rate payment frequency period-Leg 2': '',
  'Fixed rate payment frequency period multiplier-Leg 1': nan,
  'Floating rate payment frequency period multiplier-Leg 1': 1.0,
  'Fixed rate payment frequency period multiplier-Leg 2': 1.0,
  'Floating rate payment frequency period multiplier-Leg 2': nan,
  'Other payment type': '',
  'Other payment currency': '',
  'Settlement currency-Leg 1': 'USD',
  'Settlement currency-Leg 2': '',
  'Settlement location': '',
  'Collateralisation category': None,
  'Custom basket indicator': False,
  'Index factor': None,
  'Underlier ID-Leg 1': None,
  'Underlier ID-Leg 2': None,
  'Underlier ID source-Leg 1': None,
  'Underlying Asset Name': None,
  'Underlying asset subtype or underlying contract subtype-Leg 1': None,
  'Underlying asset subtype or underlying contract subtype-Leg 2': None,
  'Embedded Option type': '',
  'Option Type': None,
  'Option Style': None,
  'Package indicator': True,
  'Package transaction price': '',
  'Package transaction price currency': '',
  'Package transaction price notation': nan,
  'Package transaction spread': '0.000135',
  'Package transaction spread currency': '',
  'Package transaction spread notation': 3.0,
  'Physical delivery location-Leg 1': None,
  'Delivery Type': None,
  'Unique Product Identifier': 'QZPB5VSBGRCD',
  'UPI FISN': 'NA/Swap OIS USD',
  'UPI Underlier Name': 'USD-SOFR-OIS Compound',
  'file_date': datetime.date(2026, 7, 10)}]

In [1]:
list(df.columns)

NameError: name 'df' is not defined

In [13]:
basis_ois_upis = pd.read_csv(r'C:\Users\chris\clee\ARBS\SDRUtils\anna_dsb_upis\Rates-Swap-Basis_OIS.csv')
basis_upis = pd.read_csv(r'C:\Users\chris\clee\ARBS\SDRUtils\anna_dsb_upis\Rates-Swap-Basis.csv')
basis_upis = pd.concat([basis_upis, basis_ois_upis], ignore_index=True)
basis_upis

,TemplateVersion,Header_AssetClass,Header_InstrumentType,Header_UseCase,Header_Level,Identifier_UPI,Identifier_Status,Identifier_StatusReason,Identifier_LastUpdateDateTime,Derived_ClassificationType,...,Attributes_UnderlyingInstrumentIndexTermUnit,Attributes_OptionType,Attributes_UnderlyingInstrumentUPI,Attributes_OptionExerciseStyle,Attributes_ValuationMethodorTrigger,Derived_ReturnorPayoutTrigger,Attributes_UnderlyingAssetType,Attributes_UnderlyingInstrumentISIN,Attributes_UnderlierCharacteristic,Attributes_ReturnorPayoutTrigger
0,1,Rates,Swap,Basis,UPI,QZ6HLS5Z9BWB,New,NaN,2023-10-15 12:01:46,SRACSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Rates,Swap,Basis,UPI,QZZQ9QG7WFKX,New,NaN,2023-10-15 12:01:47,SRACSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Rates,Swap,Basis,UPI,QZRRB068536C,New,NaN,2023-10-15 12:02:42,SRACSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Rates,Swap,Basis,UPI,QZ18K4WXLJFN,New,NaN,2023-10-15 12:05:18,SRACSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Rates,Swap,Basis,UPI,QZTSTSHDLF6J,New,NaN,2023-10-15 12:10:05,SRACSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11100,1,Rates,Swap,Basis_OIS,UPI,QZ8F34ZHQXRK,New,NaN,2025-12-30 05:14:54,SRHCSC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11101,1,Rates,Swap,Basis_OIS,UPI,QZ4Q4WRG1691,New,NaN,2026-01-01 01:44:25,SRHCSC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11102,1,Rates,Swap,Basis_OIS,UPI,QZBSC9X5GW5C,New,NaN,2026-01-01 05:06:10,SRHDSC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11103,1,Rates,Swap,Basis_OIS,UPI,QZ6WFCMC0H9G,New,NaN,2026-01-06 08:14:51,SRHCSP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11104,1,Rates,Swap,Basis_OIS,UPI,QZVG8JK22D6X,New,NaN,2026-01-06 15:27:39,SRHCSC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df[(df["Unique Product Identifier"].isin(basis_upis["Identifier_UPI"])) & (df["UPI Underlier Name"].str.contains("USD"))][["UPI Underlier Name", "Effective Date", "Expiration Date", "Cleared", "Event timestamp", "Execution Timestamp"]]

,UPI Underlier Name,Effective Date,Expiration Date,Cleared,Event timestamp,Execution Timestamp
3455,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 08:34:33+00:00,2026-05-21 08:34:33+00:00
3500,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 08:37:00+00:00,2026-05-21 08:34:33+00:00
5017,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2036-05-26,I,2026-05-21 09:31:20+00:00,2026-05-21 09:31:20+00:00
5035,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2046-05-26,I,2026-05-21 09:32:07+00:00,2026-05-21 09:32:07+00:00
6638,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 11:14:19+00:00,2026-05-21 11:14:19+00:00
6667,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 11:15:47+00:00,2026-05-21 11:14:19+00:00
6737,USD-SOFR-OIS Compound vs USD-SOFR-OIS Compound,2026-05-28,2026-07-30,N,2026-05-21 11:20:00+00:00,2026-05-21 11:20:00+00:00
7110,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2027-05-26,2028-05-26,I,2026-05-21 11:41:53+00:00,2026-05-21 11:41:53+00:00
7169,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 11:45:09+00:00,2026-05-21 11:45:09+00:00
7196,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 11:45:55+00:00,2026-05-21 11:45:09+00:00
9154,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2027-03-17,2027-06-16,I,2026-05-21 13:03:39+00:00,2026-05-21 13:03:39+00:00
9235,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2036-05-26,I,2026-05-21 13:06:43+00:00,2026-05-21 13:06:43+00:00
10565,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-09-16,2026-12-16,I,2026-05-21 13:47:34+00:00,2026-05-21 13:47:34+00:00
12758,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 14:41:51+00:00,2026-05-21 14:41:51+00:00
12964,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2027-03-17,2027-06-16,I,2026-05-21 14:46:35+00:00,2026-05-21 14:46:35+00:00
13807,USD-Federal Funds-H.15-OIS-COMPOUND vs USD-SOF...,2027-03-17,2029-03-17,I,2026-05-21 15:11:06+00:00,2026-05-21 15:11:06+00:00
16128,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2026-06-26,I,2026-05-21 16:40:32+00:00,2026-05-21 16:40:32+00:00
17991,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2028-05-26,I,2026-05-21 18:39:40+00:00,2026-05-21 18:39:40+00:00
18032,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2030-05-26,I,2026-05-21 18:44:23+00:00,2026-05-21 18:44:23+00:00
18033,USD-Federal Funds-OIS Compound vs USD-SOFR-OIS...,2026-05-26,2031-05-26,I,2026-05-21 18:44:25+00:00,2026-05-21 18:44:25+00:00

In [5]:
(3.812 - 3.882) - (3.843 - 3.812)

-0.10100000000000042